# https://wiki.hypr.land/Configuring/Animations/
# bezier = NAME, X0, Y0, X1, Y1
# animation = NAME, ONOFF, SPEED, CURVE [,STYLE]

# visual inspo examples: 
# https://codepen.io/bennettfeely/pen/DOexxp
# https://www.cssportal.com/css-cubic-bezier-generator/
# https://easings.net/
# https://curveeditor.com/

animations {
    enabled = 1

    # bezier = NAME, X0, Y0, X1, Y1
    bezier = fast, 0.0, 0.97, 1.00, 1.00 # workspace movement
    bezier = brake, 0.00, 0.00, 0.01, 0.98 # window movement
    bezier = takeoff, 1.00, 0.01, 0.19, 0.99 # popup
    bezier = linear, 0, 0, 1, 1 # nothing to see here

    # animation = NAME, ONOFF, SPEED, CURVE [,STYLE]
    animation = workspaces, 1, 4, fast, slide
    animation = workspacesIn, 1, 4, fast, slide
    animation = workspacesOut, 1, 4, fast, slide
    animation = specialWorkspace, 1, 4, fast, slidevert

    animation = windows, 1, 2.5, brake, slide
    animation = windowsIn, 1, 3, brake, popin 40% 
    animation = windowsOut, 1, 3, linear, slide bottom
    animation = windowsMove, 1, 2.5, fast  
    animation = border, 1, 1, linear
    animation = borderangle, 1, 100, linear, loop 
    animation = layers, 1, 3, brake, popin 60% # parent / child

    animation = fadeIn, 1, 1, fast
    animation = fadeOut, 1, 1.2, fast
    animation = fadeSwitch, 1, 1, fast
    animation = fadeDim, 1, 1, fast
    animation = fadeShadow, 1, 1, fast
    animation = fadeLayers, 1, 1, fast

}


