# See https://wiki.hypr.land/Configuring/Keywords/

$terminal = kitty
$wezterm = wezterm
$fileManager = dolphin

$menu_drun = wofi --show drun
$menu_run = wofi --show run
$launcher = wofi

$firefox = firefox
# $chrome = chrome

$editor = $terminal nvim
$bar = waybar &

