### layout.conf | monitors, workspaces ###
# See https://wiki.hypr.land/Configuring/Monitors/

# monitor=,preferred,auto,auto # default setting

monitorv2 {
    output = DP-1
        mode = 1920x1080@144
        position = 0x0
        scale = 1 # 0.83
        transform = 1 
}

monitorv2 {
    output = DP-2
        mode = 1920x1080@143.85
        position = 1080x0
        scale = 1 # 0.83
}

# See https://wiki.hypr.land/Configuring/Gestures
# gesture = 3, horizontal, workspace

# https://wiki.hypr.land/Configuring/Variables/#input
# keyboard (desktop)
input {
    kb_layout = se
        kb_variant = nodeadkeys
# kb_options = caps:escape  # tap=ESC,hold=CAPS
        kb_options = caps:ctrl_modifier  # tap=ESC,hold=CTRL
        repeat_rate = 25 # default = 25
        repeat_delay = 300 # default = 600

        follow_mouse = 2 # follow but focus on-click. (0|1|2|3)
        sensitivity = 0 # value(-1.0<->1.0), 0 = default
        scroll_factor = 3.0 # default 1.0 
# float_switch_override_focus = 1 # only if 'follow_mouse = 1'

# touch (laptop)
        touchpad {
            disable_while_typing = true
                natural_scroll = false # if true; invert direction (no plz)
                scroll_factor = 3.0
                middle_button_emulation = false # if true; LMB+RMB = MMB
                tap-to-click = true
                drag_3fg = 0
        }
}

# Device specific configs
# https://wiki.hypr.land/Configuring/Keywords/#per-device-input-configs for more

# mouse
device {
    name = steelseries-steelseries-prime
        scroll_factor = 4
}
