# session.conf | environment + autostart #

# Autostart | UWSM 
# exec-once = systemctl --user start <name.service>
# or run cmd: 'systemctl --user enable --now <name.service> <name.service> <...etc...>' 
exec-once = systemctl --user start plasma-polkit-agent.service # polkit alt: hyprpolkitagent
exec-once = systemctl --user start hyprpaper.service
exec-once = systemctl --user start waybar.service
exec-once = systemctl --user start hyprsunset.service
exec-once = systemctl --user start cliphist-image.service 
exec-once = systemctl --user start cliphist-text.service
exec-once = systemctl --user start udiskie.service
# exec-once = qs # test -> quickshell (conf = ~/.config/quickshell/shell.qml)

# Applications 
exec-once = uwsm app -- $terminal
exec-once = uwsm app -- $firefox
exec-once = uwsm app -- $mailclient

# Environment | https://wiki.hypr.land/Configuring/Environment-variables/
# if UWSM-mode, env files are placed in | ~.config/uwsm/{env,hyprland-env}
# env = XCURSOR_SIZE,24
# env = HYPRCURSOR_SIZE,24
# env = QT_CURSOR_SIZE,24
# env = GTK_THEME,Nordic
# env = QT_AUTO_SCREEN_SCALE_FACTOR,1
# env = QT_QPA_PLATFORM,wayland;xcb
# env = QT_WAYLAND_DISABLE_WINDOWDECORATION,1
# env = QT_QPA_PLATFORMTHEME,qt5ct

# # Nvidia GPU
# env = LIBVA_DRIVER_NAME,nvidia
# env = __GLX_VENDOR_LIBRARY_NAME,nvidia

# Autostart | e.g., notifications daemons, status bars, etc.
# UWSM-managed session
# https://github.com/Vladimir-csp/uwsm 
# https://wiki.hypr.land/Useful-Utilities/Systemd-start/

## Useful commands ##
## 'systemd-cgls --user app-graphical.slice' 
## 'systemctl --user list-dependencies graphical-session.target' 
## 'systemctl --user list-units | grep autostart' 
## 'systemctl --user status <unit>' 
## 'systemctl --user list-units | grep -i <unit>'
## 'systemctl --user list-units --type=service,scope'



