# Powermenu - Wofi dmenu (ROWS / HORIZONTAL LAYOUT)

style=/home/kjs/.config/wofi/styles/dmenu-rows.css
color=/home/kjs/.config/wofi/colors
show=dmenu
gtk_dark=true
monitor=DP-2

# size and placement
width=450
height=100

columns=1
dynamic_lines=true
content_halign=center
orientation=horizontal
valign=center
halign=fill

# dynamic_lines=true
close_on_focus_loss=false
use_search_box=false
no_custom_entry=true
hide_scroll=true
hide_search=true


