# Brightness / Nightlight - Wofi dmenu
# used in: brightness.sh | power.sh | ??

style=/home/kjs/.config/wofi/styles/dmenu.css
color=/home/kjs/.config/wofi/colors
show=dmenu
gtk_dark=true
prompt=DMENU
monitor=DP-2

# size and placement
width=250
height=150
location=3
yoffset=6
xoffset=-15

content_halign=center
valign=start
# dynamic_lines=true
close_on_focus_loss=false
use_search_box=false
no_custom_entry=true
hide_scroll=true
hide_search=true


