vim.keymap.set("n", "<leader>q", "<cmd>bdelete<CR>", { desc = "Delete buffer", silent = true, noremap = true })
vim.keymap.set("n", "<C-s>", "<cmd>w<cr><esc>", { desc = "Save file", silent = true, noremap = true })
vim.keymap.set("n", "<A-j>", "<cmd>execute 'move .+' . v:count1<cr>==", { desc = "Move row down", silent = true, noremap = true })
vim.keymap.set("n", "<A-k>", "<cmd>execute 'move .-' . (v:count1 + 1)<cr>==", { desc = "Move row up", silent = true, noremap = true })
vim.keymap.set("n", "<leader>bn", "<cmd>bnext<cr>", { desc = "Next buffer", silent = true, noremap = true })
vim.keymap.set("n", "<leader>bp", "<cmd>bprevious<cr>", { desc = "Prev buffer", silent = true, noremap = true })
vim.keymap.set("n", "<leader>bd", "<cmd>bp|bd #<CR>", { desc = "Delete buf: Keep win", silent = true, noremap = true })
vim.keymap.set("n", "<leader>bo", "<cmd>enew<cr>", { desc = "Open new/empty buf", silent = true, noremap = true })
vim.keymap.set("n", "<A-Up>", "<cmd>resize +2<cr>", { desc = "Increase window height", silent = true, noremap = true })
vim.keymap.set("n", "<A-Down>", "<cmd>resize -2<cr>", { desc = "Decrease window height", silent = true, noremap = true })
vim.keymap.set("n", "<A-Left>", "<cmd>vertical resize -2<cr>", { desc = "Decrease window width", silent = true, noremap = true })
vim.keymap.set("n", "<A-Right>", "<cmd>vertical resize +2<cr>", { desc = "Increase window width", silent = true, noremap = true })

vim.keymap.set("n", "<leader><tab>n", "<cmd>tabnext<cr>", { desc = "Next tab", silent = true, noremap = true })
vim.keymap.set("n", "<leader><tab>p", "<cmd>tabprev<cr>", { desc = "Prev tab", silent = true, noremap = true })
vim.keymap.set("n", "<leader><tab>o", "<cmd>tabnew<cr>", { desc = "Open new tab", silent = true, noremap = true })

vim.keymap.set("n", "n", "'Nn'[v:searchforward].'zv'", { expr = true, desc = "Next search result", silent = true, noremap = true })
vim.keymap.set("n", "N", "'nN'[v:searchforward].'zv'", { expr = true, desc = "Prev search result", silent = true, noremap = true })
vim.keymap.set("x", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next search result", silent = true, noremap = true })
vim.keymap.set("x", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev search result", silent = true, noremap = true })
vim.keymap.set("o", "n", "'Nn'[v:searchforward]", { expr = true, desc = "Next search result", silent = true, noremap = true })
vim.keymap.set("o", "N", "'nN'[v:searchforward]", { expr = true, desc = "Prev search result", silent = true, noremap = true })

vim.keymap.set("i", "jk", "<ESC>", { desc = "Exit insert mode", silent = true, noremap = true })

-- vim.keymap.set({ "i", "x", "n", "s" }, "<Up>", info_arrow, { desc = "Disabled arrowkeys movement", silent = true, noremap = true })
-- vim.keymap.set({ "i", "x", "n", "s" }, "<Down>", info_arrow, { desc = "Disabled arrowkeys movement", silent = true, noremap = true })
-- vim.keymap.set({ "i", "x", "n", "s" }, "<Left>", info_arrow, { desc = "Disabled arrowkeys movement", silent = true, noremap = true })
-- vim.keymap.set({ "i", "x", "n", "s" }, "<Right>", info_arrow, { desc = "Disabled arrowkeys movement", silent = true, noremap = true })
