#---- Terminal
alias ls='ls --color=auto'
alias grep='grep --color=auto'

#---- alias for script loading --------
alias wsx='~/.bin/wsx.sh'
alias wsx-mount='wsx mount'
alias wsx-unmount='wsx unmount'
alias wsx-status='wsx status'
alias wsx-enter='wsx enter'

#alias mountext="~/.bin/mountwsx.sh"
#alias dismountext="~/.bin/dismountwsx.sh"
#alias untar="~/.bin/untar.sh"

#---- Dev -----------------------------
alias cck="node -e 'console.log(require('crypto').randomBytes(32).toString('hex'))'"
alias dotnetrun="dotnet run --project Main"
alias listsecrets="dotnet user-secrets list --project Main"
alias vim='nvim'

#---- System --------------------------
alias reloaddesktop="update-desktop-database ~/.local/share/applications/"
alias listaliases='grep "^alias " ~/.bash/bash_aliases'

#---- Git: worktrees ------------------
alias gwl='git worktree list'
alias gwa='git worktree add'
alias gwr='git worktree remove'

#---- UI: tree, bat -------------------
alias t1dir="tree -d -L 1"
