# alias for script loading
alias mountext="~/.bin/mountwsx.sh"
alias dismountext="~/.bin/dismountwsx.sh"
alias untar="~/.bin/untar.sh"

# dev related
alias cck="node -e 'console.log(require('crypto').randomBytes(32).toString('hex'))'"
alias dotnetrun="dotnet run --project Main"
alias listsecrets="dotnet user-secrets list --project Main"
alias vim='nvim' 

# system
alias reloaddesktop="update-desktop-database ~/.local/share/applications/"
alias listaliases='grep "^alias " ~/.bash/bash_aliases'

# git
alias gwl='git worktree list'
alias gwa='git worktree add'
alias gwr='git worktree remove'

# tree, bat(or batcat)
alias treeonedir="tree -d -L 1"

# Try to use bat if available, otherwise batcat, otherwise fall back to cat
if command -v bat &> /dev/null; then
  alias bat="bat"
elif command -v batcat &> /dev/null; then
  alias bat="batcat"
else
  alias bat="cat"
fi
