[theme-clr]

[theme-ic]
ws = 󰙀
ws-alt = 󰝘
up-arrow = 󰁝
dwn-arrow = 󰁅
exclamation = 󱈸
clock = 󱑂
clock_outline = 󱑎
calender = 󰸗
mute = 󰝟
speaker = 󰓃
drag-vertical-bar = 󱋱
drag-vertical-bar-dotted = 󰇝
drag-horizontal-bar = 󰇜
drag-horizontal-bar-dotted = 󰇜
drag-horizontal-line = 󰅹
resize-mode = 󰩨
pl-l = 
pl-r = 
home = 󰟒
firefox = 󰈹
chrome = 
steam = 󰓓
terminal = 󰞷
spotify = 󰓇
hdd = 󰋊
hdd_remove = 󱁌
hdd_add = 󱁋
ram = 
memory = 󰍛
; cpu = 󰻠
cpu = 
power = 󰐥
sleep = 󰤄
restart = 󰜉
close = 󱎘
warn = 
temp_high = 
temp_high2 = 󱃂
mail_add = 󰧫
mail = 󰇮
keyboard = 󰌓
kb_caps = 󰌎
kb_caps2 = 󰪛

[settings]
screenchange-reload = true
enable-ipc = true
; compositing-background = source
; compositing-foreground = over
; compositing-overline = over
; compositing-underline = over
; compositing-border = over
;
; psuedo-transparency = true

[bar/bubblebase]
monitor-exact = true
override-redirect =
bottom = false
fixed-center = true
enable-ipc = true
width = 100%
height = 25
offset-x = 0
offset-y = 0

background = ${colors.none}
foregroudn = ${colors.fg}

radius = 0.0
line-size = 2
line-color = ${colors.none}

border-top-size = 8
border-top-color = ${colors.none}

border-left-size = 8
border-left-color = ${colors.none}

border-right-size = 8
border-right-color = ${colors.none}

border-bottom-size = 8
border-bottom-color = ${colors.none}

padding = 0

font-0 = "IosevkaTerm NFM:size=10;2"
font-1 = "IosevkaTerm NFM:size=12;3:weight=Bold"
font-2 = "JetBrainsMono NFM:size=12;3:style=SemiBold"

; usage: font-3: usage `font = 4` === module symbols
font-3 = "Symbols Nerd Font:size=12;2"
; usage font-4: usage: `font = 5` === powerline symbols
font-4 = "Symbols Nerd Font:size=19;4"

dim-value = 1.0
wm-name = i3
; dpi = 0
; dpi-x = 96
; dpi-y = 96

double-click-interval = 400
cursor-click = pointer
cursor-scroll = ns-resize


;-------------------------------------;
; --> Primary Top Position Bar
;-------------------------------------;
[bar/main]
inherit = bar/bubblebase
monitor = "DP-2"
modules-left = pl i3ws pr
modules-center = pl kde pr
modules-right = = pl nightlight pr s pl netud pr s pl audio pr s pl date time pr

;-------------------------------------;
; --> Primary Bottom Position Bar
;-------------------------------------;
[bar/mainbottom]
inherit = bar/bubblebase
monitor = "DP-2"
bottom = true
modules-left = pl open_home open_firefox open_chrome open_term open_spotify pr
; modules-center = pl spotify pr
modules-center =  spotify
modules-right = pl powermenu pr

;-------------------------------------;
; --> Secondary Bottom Position Bar
;-------------------------------------;
[bar/secondary]
inherit = bar/bubblebase
monitor = "DP-0"
bottom = true
modules-left = pl ext1 ext2 pr
modules-center = pl cpu-temp cpu pr s pl memory pr
modules-right = pl xkeyboard pr s pl  powermenu pr

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;;; POWERLINE BUBBLES -> MODULES STYLING ;;;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; powerline bubble-ic left
[module/pl]
type = custom/text
format-background = ${colors.none}
format-foreground = ${colors.bg-hex}
format = ${theme-ic.pl-l}
format-font = 5

; powerline bubble-ic right
[module/pr]
type = custom/text
format-background = ${colors.none}
format-foreground = ${colors.bg-hex}
format = ${theme-ic.pl-r}
format-font = 5

; transparent spacing
[module/s]
type = custom/text
format = " "
format-foreground = ${colors.none}

; colored spacing
; [module/sbg]
; type = custom/text
; format = " "
; format-foreground = ${colors.bg}
; format-background = ${colors.bg}


;-------------------------------------;
; --> i3ws
[module/i3ws]
type = internal/i3
; pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = false
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true

format = <label-state><label-mode>
format-prefix = ${theme-ic.ws}
format-prefix-font = 4
format-prefix-padding = 1
format-prefix-background = ${colors.bg-hex}

label-mode = %mode%
label-mode-background = ${colors.bg-hex}
label-mode-foreground = ${colors.warn}
label-mode-font = 2
label-mode-padding = 1

; active = current ws placement
label-focused = %name%
label-focused-underline = ${colors.hilite-alt}
label-focused-background = ${colors.bg-hex}
label-focused-padding = 1
label-focused-font = 1

; unfocused = inactive ws on any monitor
label-unfocused = %index%
label-unfocused-padding = 1
label-unfocused-font = 1
label-unfocused-foreground = ${colors.fg-alt}
label-unfocused-background = ${colors.bg-hex}

; visible = non-active visible ws
label-visible = %name%
label-visible-padding = 1
label-visible-font = 1
label-visible-background = ${colors.bg-hex}
label-visible-underline = ${colors.accent}

label-urgent = %index%
label-urgent-padding = 1
label-urgent-font = 1
label-urgent-foreground = ${colors.warn}
label-urgent-background = ${colors.bg}

; [module/bi3mode]
; type = internal/i3
; format = <label-mode>
;
; format-prefix = ${theme-ic.resize-mode}
; format-prefix-font = 4
; format-prefix-padding = 1
; format-prefix-background = ${colors.bg-hex}
; label-mode = %mode%
; label-mode-padding = 1
; label-mode-background = ${colors.warn}
; label-mode-foreground = ${colors.fg-dark}
; label-mode-font = 1
;


;-------------------------------------;
; --> network-stats (up|down-speed)
[module/netud]
type = internal/network
interval = 5
interface-type = wired

format-connected-prefix = ${theme-ic.up-arrow}
format-connected-prefix-font = 4
format-connected-prefix-padding-left = 1
format-connected-prefix-foreground = ${colors.warn}
format-connect-prefix-background = ${colors.bg-hex}
format-connected = <label-connected>
format-connected-background = ${colors.bg-hex}

; label-connected = "%upspeed:7% %{T4}%{F#EBCB8B}󰛴%{T-}%{F-}%downspeed:7%"
label-connected = "%upspeed:7% %{T4}%{F#A3BE8C}󰁅%{T-}%{F-}%downspeed:7%"
label-connected-padding-right = 1



;-------------------------------------;
; --> Time & Date
[date-base]
type = internal/date
interval = 1
format-prefix-background = ${colors.bg-hex}
label-background = ${colors.bg-hex}

[module/time]
inherit = date-base
time = %H:%M

format = <label>
format-prefix-font = 4
format-prefix = ${theme-ic.clock_outline}
format-prefix-padding-right = 1
format-prefix-background = ${colors.bg-hex}

label = %time%
label-background = ${colors.bg-hex}
label-font = 1
; label-padding-right = 1

; date
[module/date]
inherit = date-base
date = %Y-%m-%d%

format = <label>
format-prefix-font = 4
format-prefix = ${theme-ic.calender}
format-prefix-padding-right = 1

label = %date%
label-padding-right = 1
label-font = 1



;-------------------------------------;
; --> pulseaudio
; interval 5% per scroll
; ui-max = ~153%

[module/audio]
type = internal/pulseaudio
interval = 25
use-ui-max = false

format-volume = <label-volume> <bar-volume>
format-volume-background = ${colors.bg-hex}
format-muted = <label-muted>
format-muted-background = ${colors.bg-hex}

label-volume-prefix= ${theme-ic.speaker}
label-volume = %percentage%%
label-volume-padding = 1

; label-muted-padding = 4
label-muted = ${theme-ic.mute}
label-muted-font = 4
label-muted-foreground = ${colors.crit}
label-muted-underline = ${colors.crit}

bar-volume-width = 4
bar-volume-foreground-0 = ${colors.warn}
bar-volume-foreground-1 = ${colors.warn}
bar-volume-foreground-2 = ${colors.ok}
bar-volume-foreground-3 = ${colors.ok}
bar-volume-foreground-4 = ${colors.ok}
bar-volume-gradient = false
bar-volume-background-0 = ${colors.bg-hex}

bar-volume-indicator = ${theme-ic.drag-vertical-bar}
bar-volume-indicator-font = 4
bar-volume-indicator-foreground = ${colors.fg}
bar-volume-indicator-background = ${colors.bg-hex}

bar-volume-fill = ${theme-ic.drag-horizontal-line}
bar-volume-fill-font = 4
bar-volume-fill-background = ${colors.bg-hex}

bar-volume-empty = ${theme-ic.drag-horizontal-line}
bar-volume-empty-font = 4
bar-volume-empty-background = ${colors.bg-hex}

click-right = pavucontrol



;-------------------------------------;
;--> Filesystem / Mounted Drives

[fs-base]
type = internal/fs
interval = 50
fixed-values = true

format-mounted-prefix-font = 4
format-mounted-prefix = ${theme-ic.hdd_add}
format-mounted-prefix-padding = 1
format-mounted-prefix-foreground = ${colors.ok}
format-mounted-prefix-background = ${colors.bg-hex}
format-mounted = <label-mounted>

format-unmounted-prefix-font = 4
format-unmounted-prefix = ${theme-ic.hdd_remove}
format-unmounted-prefix-padding = 1
format-unmounted-prefix-foreground = ${colors.crit}
format-unmounted-prefix-background = ${colors.bg-hex}
format-unmounted = <label-unmounted>

label-mounted-padding-right = 1
label-mounted-font = 1

label-unmounted =  %mountpoint%
label-unmounted-foreground = ${colors.fg-alt}
label-unmounted-background = ${colors.bg-hex}
label-unmounted-font = 1

; [module/fs-root]
; inherit = fs-base
; mount-0 = /
; label-mounted = / %free%

[module/ext1]
inherit = fs-base
mount-0 = /media/veracrypt1
label-mounted = ext1 %free%
label-mounted-background = ${colors.bg-hex}

[module/ext2]
inherit = fs-base
mount-0 = /media/veracrypt2
label-mounted = ext2/ %free%
label-mounted-background = ${colors.bg-hex}


;-------------------------------------;
;--> Memory Load (RAM)
[module/memory]
type = internal/memory
interval = 5
warn-percentage = 80

format = <label>
format-prefix-font = 4
format-prefix = ${theme-ic.ram}
format-prefix-background = ${colors.bg-hex}
format-prefix-padding = 1

label = %gb_used%/%gb_total%
label-background = ${colors.bg-hex}
label-padding-right = 1
label-font = 1


;-------------------------------------;
; --> Processor Load (CPU)
[module/cpu]
type = internal/cpu
interval = 10

format-prefix-font = 4
format-prefix = ${theme-ic.cpu}
format-prefix-background = ${colors.bg-hex}
; format-prefix-padding = 1

label = %percentage:2%
label-foreground = ${colors.fg}
label-background = ${colors.bg-hex}
label-font = 1

[module/cpu-temp]
type = internal/temperature
interval = 20
thermal-zone = 1
warn-temperature = 80

format = <label>

label = %temperature-c%
label-font = 1
label-padding = 1
label-background = ${colors.bg-hex}

format-warn-prefix-font = 4
format-warn-prefix = ${theme-ic.warn}
format-warn-prefix-background = ${colors.bg-hex}
format-warn-prefix-foreground = ${colors.warn}
format-warn-prefix-padding = 1

format-warn = <label-warn>

label-warn = %temperature-c%
label-warn-foreground = ${colors.crit}
label-warn-background = ${colors.bg-hex}
label-warn-padding-right = 1
label-warn-font = 1



;-------------------------------------;
;--> Powermenu (off/reboot)
; change to rofi?
[module/powermenu]
type = custom/menu
expand-right = true

label-open = ${theme-ic.power}
label-open-font = 4
label-open-background = ${colors.bg-hex}
label-open-padding = 1

label-close = ${theme-ic.close}
label-close-font = 4
label-close-background = ${colors.bg-hex}
label-close-foreground = ${colors.hilite}

label-separator = |
label-separator-foreground = ${colors.sep}
label-separator-background = ${colors.bg-hex}
label-separator-padding = 1

menu-0-0 = %{B#2E3440}%{T1}%{F-}restart %{T4}%{F#BF6161}󰜉 %{T-}%{F-}
menu-0-0-exec = #powermenu.open.1
menu-0-1 = %{B#2E3440}%{T1}%{F-}shutdown %{T4}%{F#BF6161}󰐥 %{T-}%{F-}
menu-0-1-exec = #powermenu.open.2

menu-1-0 = %{B#2E3440}%{T1}%{F-}cancel %{T4}%{F#A3BE8C}󱎘 %{T-}%{F-}
menu-1-0-exec = #menu-powermenu.open.0
menu-1-1 = %{B#2E3440}%{T1}%{F-}restart %{T4}%{F#BF6161}󰜉 %{T-}%{F-}
menu-1-1-exec = reboot

menu-2-0 = %{B#2E3440}%{T1}%{F-}shutdown %{T4}%{F#BF6161}󰐥 %{T-}%{F-}
menu-2-0-exec = poweroff
menu-2-1 = %{B#2E3440}%{T1}%{F-}cancel %{T4}%{F#A3BE8C}󱎘 %{T-}%{F-}
menu-2-1-exec = #powermenu.open.0


;-------------------------------------;
; --> Keyboard (lng/caps/nlock)
[module/xkeyboard]
type = internal/xkeyboard

blacklist-0 = num lock
; blacklist-1 = caps lock

format = <label-layout><label-indicator>
format-spacing =
format-background = ${colors.bg-hex}

format-prefix = ${theme-ic.keyboard}
format-prefix-background = ${colors.bg-hex}
format-prefix-foreground = ${colors.hilite}
format-prefix-padding = 1
format-prefix-font = 4

; label-layout = %name%
label-layout = %layout%
label-layout-background = ${colors.bg-hex}
label-layout-foreground = ${colors.fg-alt}
label-layout-font = 1

format-indicator-background = ${colors.bg-hex}
label-indicator-background = ${colors.hilite}

indicator-icon-default =
indicator-icon-0 = caps lock;%{B#2E3440}-CL;%{B#2E3440}%{T4} %{F#EBCB8B}󰌎%{T-}+CL%{F-}
indicator-icon-1 = scroll lock;-SL;+SL
indicator-icon-2 = num lock;-NL;+NL

label-indicator-on-capslock = %icon%
label-indicator-off-capslock =
label-indicator-on-numlock =
label-indicator-off-numlock =


;-------------------------------------;
; Custom Modules|Scripts Below
;-------------------------------------;

;-------------------------------------;
; --> KDECONNECT
; [module/kdec]
; type = custom/script
; ; exec = ~/.bin/polybar/kdeconnect.sh --verbose
; interval = 10
; label = %output%
; ; click-left = ~/.bin/polybar/kdeconnect.sh --menu


;-------------------------------------;
;;; App Launcher ;;;
[open-base]
type = custom/text
format-font = 4
format-padding = 1
format-background = ${colors.bg-hex}

[module/open_home]
inherit = open-base
format = ${theme-ic.home}
click-left = nautilus ~

[module/open_firefox]
inherit = open-base
format = ${theme-ic.firefox}
click-left = firefox

[module/open_chrome]
inherit = open-base
format = ${theme-ic.chrome}
click-left = google-chrome

; [module/open_steam]
; inherit = open-base
; format = ${theme-ic.steam}
; ; click-left = steam

[module/open_term]
inherit = open-base
format = ${theme-ic.terminal}
click-left = wezterm

[module/open_spotify]
inherit = open-base
format = ${theme-ic.spotify}
click-left = spotify


;-------------------------------------;
;;; Spotify / Media ;;;
[module/spotify]
type = custom/script
exec = ~/.bin/polybar/spotify.sh
tail = true
label = %output%

[module/nightlight]
type = custom/ipc
hook-0 = ~/.bin/polybar/nightlight.sh --print
initial = 1
click-left = bash -lc '~/.bin/polybar/nightlight.sh --toggle; polybar-msg hook nightlight 1 >/dev/null'
format = <output>
format-background = ${colors.bg-hex}
format-padding = 1
label = %output%

[module/kde]
type = custom/ipc
hook-0 = ~/.bin/polybar/kde.sh --print
initial = 1
click-left = bash -lc '~/.bin/polybar/kde.sh --menu; polybar-msg hook kde 1 >/dev/null'
format = <output>
format-background = ${colors.bg-hex}
format-padding = 1
label = %output%

