;----------------------------
;; Primary DP(-2) - WS: pdws
;----------------------------
[bar/pdws]
inherit = bar/base
monitor = "DP-2"
override-redirect = true
; wm-restack = i3
bottom = false
width = 10%
height = 22
background = ${colors.bg-alt}
; background = #f00
border-top-size = 1
border-bottom-size = 1
border-right-size = 1
border-left-size = 1
border-color = #fff
radius = 7

offset-y = 0.2%
offset-x = 3%

; modules-left = i3
modules-center = i3

;----------------------------
;; Primary D(P-2) - Time-Date
;; bar name: pdtd
;----------------------------
[bar/pdtd]
inherit = bar/base
monitor = "DP-2"
override-redirect = true
; wm-restack = i3
bottom = false
width = 13%
height = 22
background = ${colors.bg-alt}
; background = #f00
border-top-size = 1
border-bottom-size = 1
border-right-size = 1
border-left-size = 1
border-color = #fff
radius = 7

offset-y = 0.2%
offset-x = 84%

; modules-left = i3
modules-center = time date

;----------------------------
;; Primary D(P-2) - Launcher
;; bar name: pdl
;----------------------------
[bar/pdl]
inherit = bar/base
monitor = "DP-2"
override-redirect = true
; wm-restack = i3
bottom = true
width = 13%
height = 22
background = ${colors.bg-alt}
; background = #f00
border-top-size = 1
border-bottom-size = 1
border-right-size = 1
border-left-size = 1
border-color = #fff
radius = 7

offset-y = 1%
; offset-x = 84%
offset-x = 3%
modules-center = open_home open_firefox open_steam open_term open_spotify
