[ic-audio]
volume-high = 󰕾
volume-low = 󰕿
volume-medium = 󰖀
volume-mute = 󰝟
volume-off = 󰖁
volume-source = 󱄠

drag-vertical-bar = 󱋱
drag-vertical-bar-dotted = 󰇝
drag-horizontal-bar = 󰇜
drag-horizontal-bar-dotted = 󰇜
drag-horizontal-line = 󰅹


;----------------------------
;; Audio / PulseAudio / PipeWire
;----------------------------
[module/pulseaudio]
type = internal/pulseaudio
; raise volume with 10 for each scroll
interval = 10

; ui-max = ~153%
use-ui-max = true
format-volume = <ramp-volume> <label-volume> <bar-volume>
format-volume-foreground = ${colors.fg}

label-volume = %percentage%%

; format-muted-prefix = 
; format-muted-prefix = ${ic-audio.volume-mute}
; format-muted-prefix-font = 4
; format-muted-prefix-padding-right = 1
format-muted-foreground = ${colors.fg-dim}
format-muted-underline = ${colors.crit}

; label-muted = muted
label-muted = ${ic-audio.volume-mute}
label-muted-font = 4
label-muted-padding = 1
label-muted-foreground = ${colors.crit}

bar-volume-width = 5
bar-volume-foreground-0 = ${colors.warn}
bar-volume-foreground-1 = ${colors.warn}
bar-volume-foreground-2 = ${colors.ok}
bar-volume-foreground-3 = ${colors.ok}
bar-volume-foreground-4 = ${colors.ok}

bar-volume-gradient = false

bar-volume-indicator = ${ic-audio.drag-vertical-bar}
bar-volume-indicator-font = 4
bar-volume-indicator-foreground = ${colors.fg}

bar-volume-fill = ${ic-audio.drag-horizontal-line}
bar-volume-fill-font = 4

bar-volume-empty = ${ic-audio.drag-horizontal-line}
bar-volume-empty-font = 4

ramp-volume-0 = ${ic-audio.volume-low}
ramp-volume-1 = ${ic-audio.volume-medium}
ramp-volume-2 = ${ic-audio.volume-high}
ramp-volume-font = 4

; open menu
click-right = pavucontrol
