[ic-audio]
volume-high = 󰕾
volume-low = 󰕿
volume-medium = 󰖀
volume-mute = 󰝟
volume-off = 󰖁
volume-source = 󱄠

drag-vertical-bar = 󱋱
drag-vertical-bar-dotted = 󰇝
drag-horizontal-bar = 󰇜
drag-horizontal-bar-dotted = 󰇜
drag-horizontal-line = 󰅹


;----------------------------
;; Audio / PulseAudio / PipeWire
;----------------------------
[module/pulseaudio]
type = internal/pulseaudio
; raise volume with 10 for each scroll
interval = 10
; ui-max = ~153%
use-ui-max = true
; format-volume = <ramp-volume> <label-volume>
format-volume = <ramp-volume> <label-volume> <bar-volume>
format-volume-foreground = ${colors.fg}
format-volume-background = ${colors.bg-hex}

label-volume = %percentage%%
label-volume-padding = 2
label-volume-background = ${colors.bg-hex}

label-muted = ${ic-audio.volume-mute}
label-muted-font = 4
label-muted-padding = 1
label-muted-foreground = ${colors.crit}

format-muted-foreground = ${colors.fg-alt}
format-muted-background = ${colors.bg-hex}
format-muted-underline = ${colors.crit}

; bar-volume-width = 5
; bar-volume-foreground-0 = ${colors.warn}
; bar-volume-foreground-1 = ${colors.warn}
; bar-volume-foreground-2 = ${colors.ok}
; bar-volume-foreground-3 = ${colors.ok}
; bar-volume-foreground-4 = ${colors.ok}
; bar-volume-gradient = false
; bar-volume-background-0 = ${colors.bg-hex}

; bar-volume-indicator = ${ic-audio.drag-vertical-bar}
; bar-volume-indicator-font = 4
; bar-volume-indicator-foreground = ${colors.fg}
; bar-volume-indicator-background = ${colors.bg-hex}

bar-volume-fill = ${ic-audio.drag-horizontal-line}
bar-volume-fill-font = 4
bar-volume-fill-background = ${colors.bg-hex}

bar-volume-empty = ${ic-audio.drag-horizontal-line}
bar-volume-empty-font = 4
bar-volume-empty-background = ${colors.bg-hex}

; ramp-volume-0 = ${ic-audio.volume-low}
; ramp-volume-1 = ${ic-audio.volume-medium}
; ramp-volume-2 = ${ic-audio.volume-high}
; ramp-volume-font = 4
; ramp-volume-backgrund = ${colors.bg-hex}

; format-muted-prefix = 
; format-muted-prefix = ${ic-audio.volume-mute}
; format-muted-prefix-font = 4
; format-muted-prefix-padding-right = 1
; open menu
click-right = pavucontrol


;;; for bubblesbar
; interval = 5% per scroll | ui-max = ~153%
[module/audio]
type = internal/pulseaudio
interval = 5
use-ui-max = true

format-volume = <ramp-volume> <label-volume>
format-volume-background = ${colors.bg-hex}
format-muted = <label-muted>
format-muted-background = ${colors.bg-hex}


label-volume = %percentage%%
label-volume-padding = 1


label-muted = ${ic-audio.volume-mute}
label-muted-font = 4
; label-muted-padding = 4
label-muted-foreground = ${colors.crit}
label-muted-underline = ${colors.crit}

ramp-volume-0 = ${ic-audio.volume-low}
ramp-volume-1 = ${ic-audio.volume-medium}
ramp-volume-2 = ${ic-audio.volume-high}
ramp-volume-font = 4

click-right = pavucontrol

; bar-volume-width = 5
; bar-volume-foreground-0 = ${colors.warn}
; bar-volume-foreground-1 = ${colors.warn}
; bar-volume-foreground-2 = ${colors.ok}
; bar-volume-foreground-3 = ${colors.ok}
; bar-volume-foreground-4 = ${colors.ok}
; bar-volume-gradient = false
