[ic-datetime]
clock = 󱑂
clock_outline = 󱑎
calender = 󰸗

;----------------------------
;; Date / Time
;----------------------------

[date-base]
type = internal/date
interval = 1
format-prefix-background = ${colors.bg-hex}
label-background = ${colors.bg-hex}

[module/time]
inherit = date-base
time = %H:%M

format = <label>
format-prefix-font = 4
format-prefix = ${ic-datetime.clock_outline}
format-prefix-padding-right = 1
format-prefix-background = ${colors.bg-hex}

label = %time%
label-background = ${colors.bg-hex}
label-font = 1

[module/date]
inherit = date-base
date = %Y-%m-%d%

format = <label>
format-prefix-font = 4
format-prefix = ${ic-datetime.calender}
format-prefix-padding-right = 1

label = %date%
label-background = ${colors.bg-hex}
label-font = 1


