[ic-filesystem]
hdd = 󰋊
hdd_remove = 󱁌
hdd_add = 󱁋

;----------------------------
;; Filesystem
;----------------------------
[fs-base]
type = internal/fs
interval = 50
fixed-values = true

; nf-fa-hard_drive
; format-mounted-prefix = 
format-mounted-prefix-font = 4
format-mounted-prefix = ${ic-filesystem.hdd}
format-mounted-prefix-padding = 1
format-mounted = <label-mounted>
format-mounted-prefix-foreground = ${colors.ok}

label-mounted-padding = 1
label-mounted-font = 1

; nf-fa-xmark
; format-unmounted-prefix = 
format-unmounted-prefix-font = 4
format-unmounted-prefix = ${ic-filesystem.hdd_remove}
format-unmounted-prefix-padding = 1
format-unmounted-prefix-foreground = ${colors.crit}
format-unmounted = <label-unmounted>

label-unmounted =  %mountpoint%
label-unmounted-foreground = ${colors.fg-dim}
label-unmounted-font = 1

[module/fs-root]
inherit = fs-base
mount-0 = /
label-mounted = / %free%

; TODO: add custom .sh-script to get whole disk space ? or not ?
[module/fs-ext]
inherit = fs-base
mount-0 = /media/veracrypt2
label-mounted = ext/ %free%

