[ic-i3ws]
workspaces = 󰙀
workspaces-alt = 󰝘
separator = 

; [module/i3-divider-right]
; inherit = powerline-base
; format = ${ic-powerline.hard-divider-right}
;
; [module/i3-divider-left]
; inherit = powerline-base
; format = ${ic-powerline.hard-divider-left}
; format-background = ${colors.bg}
; format-foreground = ${colors.accent-alt}
; format-margin-right = 1
;----------------------------
;; Workspaces
;----------------------------

[module/i3]
type = internal/i3
; pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = false
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true
; format-background = ${colors.accent-alt}
; format-padding = 1

ws-icon-0 = 1
ws-icon-1 = 2
ws-icon-2 = 3
ws-icon-3 = 4
ws-icon-4 = 5


format = <label-state> <label-mode>
format-prefix = ${ic-i3ws.workspaces}
format-prefix-font = 4
format-prefix-padding-right = 1


label-mode = %mode%
label-mode-padding = 1
label-mode-background = ${colors.warn}
label-mode-foreground = ${colors.fg-dark}
label-mode-font = 1

label-focused = %name%
label-focused-underline = ${colors.hilite-alt}
label-focused-padding = 1
label-focused-font = 2

; unfocused = inactive ws on any monitor
label-unfocused = %index%
label-unfocused-padding = 1
label-unfocused-font = 1
label-unfocused-foreground = ${colors.fg-alt}

; visible = active ws on onfocused monitor
label-visible = %name%
label-visible-padding = 1
label-visible-font = 1

label-urgent = %index%
label-urgent-padding = 1
label-urgent-font = 1
label-urgent-foreground = ${colors.hilite-alt}



