[ic-launcher]
; apps = 󰀻
; apps-alt = 󰵆
; apps-close = 󱎘
home = 󰟒
firefox = 󰈹
steam = 󰓓
terminal = 󰞷
spotify = 󰓇

;----------------------------
;; Applications
; add  .sh-scripts or .py
;----------------------------
; old
[open-base]
type = custom/text
format-font = 4
; format-padding-left= 1

;;; TEMPLATE ;;;
; [module/open_???]
; inherit = open-base
; format = ${ic-launcher.???}
; click-left = ~/.config/polybar/scripts.open.sh "cmd"

[module/open_home]
inherit = open-base
format = ${ic-launcher.home}
click-left = nautilus ~

[module/open_firefox]
inherit = open-base
format = ${ic-launcher.firefox}
click-left = firefox

[module/open_steam]
inherit = open-base
format = ${ic-launcher.steam}
; click-left = steam

[module/open_term]
inherit = open-base
format = ${ic-launcher.terminal}
click-left = wezterm

[module/open_spotify]
inherit = open-base
format = ${ic-launcher.spotify}
click-left = spotify


