;; find modules info and more:
; https://github.com/polybar/polybar/wiki

;----------------------------
;; network - wired/wireless/bt
;----------------------------

; [colors]
; hlite = #1C1C1F
; red = #692B2B
; green = #4B692B
; purple = #572B69

;; default base
[network-base]
type = internal/network
interval = 5
; format-connected = <label-connected>
; format-disconnected = <label-disconnected>
; format-disconnected =
; format-disconnected-prefix =
; label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
; label-disconnected-foreground = ${colors.red}

;; cable
[module/eth]
inherit = network-base
interface-type = wired
label-connected = %local_ip%

; format connected
format-connected-prefix = "󰱓 󰈀 "
; format-connected-prefix-foreground =
format-connected = <label-connected>

; format disconnected

; wireless
[module/wlan]
inherit = network-base
interface-type = wireless
label-connected = wlan: %essid%

; label-connected-foreground =
format-connected  = <ramp-signal> <label-connected>
format-connected-underline =

;; ramp-signal-* icons = nf-md-network-strength_* (* = 1-4)
ramp-signal-0 = "󰣴"
ramp-signal-1 = "󰣶
ramp-signal-3 = "󰣸"
ramp-signal-4 = "󰣺"

; ramp-signal-foreground = ${colors.fg_light}


