[ic-network]
ip = 󰩟
upspeed = 󰜸
upspeed-alt = 󰁝
downspeed-alt = 󰁅
downspeed = 󰜯
exclamation = 󱈸

[ic-eth]
cable_connected = 󰈁
cable_disconnected = 󰈂

[ic-wlan]
network-strength-1 = 󰣴
network-strength-2 = 󰣶
network-strength-3 = 󰣸
network-strength-4 = 󰣺
network-strength-4-alert = 󰣻
network-strength-off = 󰣼
network-strength-off-outline = 󰣽


;----------------------------
;; Network Connections
;----------------------------

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

; wireless = laptop
[module/wlan]
inherit = network-base
interface-type = wireless

format-connected = <ramp-signal> <label-connected>

label-disconnected =
;label-disconnected = ${ic-wlan.network-strength-off}
label-disconnected-font = 4
label-disconnected-foreground = ${colors.crit}

ramp-signal-0 = ${ic-wlan.network-strength-1}
ramp-signal-1 = ${ic-wlan.network-strength-2}
ramp-signal-2 = ${ic-wlan.network-strength-3}
ramp-signal-3 = ${ic-wlan.network-strength-4}

animation-packetloss-0 = ${ic-wlan.network-strength-4-alert}
animation-packetloss-0-foreground = ${colors.warn}
animation-packetloss-1 = ${ic-network.exclamation}
animation-packetloss-1-foreground = ${colors.warn}
animation-packetloss-framrate = 500



; cable = desktop
[module/eth]
inherit = network-base
interface-type = wired

format-connected-prefix-font = 4
format-connected-prefix = ${ic-network.ip}
format-connected-prefix-foreground = ${colors.ok}
format-connected-prefix-padding = 1

label-connected = %linkspeed%
label-padding = 1

label-disconnected = ${ic-eth.cable_disconnected}
label-disconnected-foreground = ${colors.crit}

;----------------------------
;; Network Speed (UP/DOWN)
;----------------------------


; eth+wlan + up/down
; add ENV for interface ? to get dynamic value either eth/wlan
[module/networkspeed]
; type = internal/network
inherit = network-base
interface-type = wired

; format-connected-prefix = ${ic-network.upspeed-alt}
format-connected-prefix = 󰛶
format-connected-prefix-font = 4
format-connected-prefix-padding-left = 1
format-connected-prefix-foreground = ${colors.ok}
format-connect-prefix-background = ${colors.bg-hex}
format-connected = <label-connected>
format-connected-background = ${colors.bg-hex}

; label-connected = "%upspeed:7% %{T4}%{F#EBCB8B}󰁅%{T-}%{F-}%downspeed:7%"
label-connected = "%upspeed:7% %{T4}%{F#EBCB8B}󰛴%{T-}%{F-}%downspeed:7%"
label-connected-padding-right = 1


; cable speed up
[module/eth-upspeed]
inherit = network-base
interface-type = wired
accumulate-stats = true
unknown-as-up = true

format-connected-prefix-font = 4
format-connected-prefix = ${ic-network.upspeed}
format-connected-prefix-foreground = ${colors.warn}
format-connected-prefix-padding-right = 1
label-connected =  %upspeed%
label-disconnected =

; cable speed down
[module/eth-downspeed]
inherit = network-base
interface-type = wired
accumulate-stats = true
unknown-as-up = true

format-connected-prefix-font = 4
format-connected-prefix = ${ic-network.downspeed}
format-connected-prefix-foreground = ${colors.ok}
format-connected-prefix-padding-right = 1
format-connected = <label-connected>
label-connected =  %downspeed%
label-disconnected =

; wlan speed up
[module/wlan-upspeed]
inherit = network-base
interface-type = wireless
accumulate-stats = true
unknown-as-up = true

format-connected-prefix-font = 4
format-connected-prefix = ${ic-network.upspeed}
format-connected-prefix-foreground = ${colors.warn}
format-connected-prefix-padding-right = 1
label-connected =  %upspeed%
label-disconnected =

; wlan speed down
[module/wlan-downspeed]
inherit = network-base
interface-type = wireless
accumulate-stats = true
unknown-as-up = true

format-connected-prefix-font = 4
format-connected-prefix = ${ic-network.downspeed}
format-connected-prefix-foreground = ${colors.ok}
format-connected-prefix-padding-right = 1
format-connected = <label-connected>
label-connected =  %downspeed%
label-disconnected =
