; [ic-powerline]
; pixelated_square_big = 
; pixelated_square_big_mirror = 
; pixelated_square_small = 
; pixelated_square_small_mirror = 
; half_circle_thin_right = 
; half_circle_thin_left = 
; half_circle_thick_right = 
; half_circle_thick_left = 
; hard-divider-right = 
; hard-divider-left = 



;----------------------------
;; Powerline Glyphs
;----------------------------
;
; [powerline-base]
; type = custom/text
; format-font = 4
; ; format-background = ${colors.bg-alt}
; ; format-foreground = ${colors.accent-alt}
;
; [module/divider-right]
; inherit = powerline-base
; format = ${ic-powerline.hard-divider-right}
;
; [module/divider-left]
; inherit = powerline-base
; format = ${ic-powerline.hard-divider-left}
; [module/pl-square-lg-right]
; inherit = powerline-base
; format = ${ic-powerline.pixelated_square_big}
;
; [module/pl-square-lg-left]
; inherit = powerline-base
; format = ${ic-powerline.pixelated_square_big_mirror}
;
; [module/pl-circle-thin-right]
; inherit = powerline-base
; format = ${ic-powerline.half_circle_thin_right}
;
; [module/pl-circle-thin-left]
; inherit = powerline-base
; format = ${ic-powerline.half_circle_thin_left}
;
; [module/pl-hard-divider-right]
; inherit = powerline-base
; format = ${}
;
; [module/pl-hard-divider-left]
; inherit = powerline-base
; format = ${ic-powerline.hard-divider-left}
