[ic-pmenu]
power = 󰐥
sleep = 󰤄
restart = 󰜉

[labels/powermenu]
root-reboot =  󰜉
;----------------------------
;; Power (off/restart/logout)
;----------------------------

[module/powermenu]
type = custom/menu
expand-right = true

format-spacing = 1

label-open = ${ic-pmenu.power}
label-open-font = 4
; label-open-foreground = ${colors.hilite}

label-close = ${ic-general.close-circle-outline}
label-close-font = 4
label-close-foreground = ${colors.hilite}
label-separator = |
label-separator-foreground = ${colors.sep}

;root: lvl-0
menu-0-0 = %{T1}%{F-}restart %{T4}%{F#BF6161}󰜉 %{T-}%{F-}
menu-0-0-exec = #powermenu.open.1
menu-0-1 = %{T1}%{F-}shutdown %{T4}%{F#BF6161}󰐥 %{T-}%{F-}
menu-0-1-exec = #powermenu.open.2

;reboot confirm: lvl-1
menu-1-0 = %{T1}%{F-}cancel %{T4}%{F#A3BE8C}󱎘 %{T-}%{F-}
menu-1-0-exec = #menu-powermenu.open.0
menu-1-1 = %{T1}%{F-}restart %{T4}%{F#BF6161}󰜉 %{T-}%{F-}
menu-1-1-exec = reboot

; shutdown
menu-2-1 = %{T1}%{F-}cancel %{T4}%{F#A3BE8C}󱎘 %{T-}%{F-}
menu-2-1-exec = #powermenu.open.0

menu-2-0 = %{T1}%{F-}shutdown %{T4}%{F#BF6161}󰐥 %{T-}%{F-}
menu-2-0-exec = poweroff


