; requires playerctl
; based on:
; https://github.com/PrayagS/polybar-spotify/tree/master

; [ic-spotify]
; play-alt = 󰐊
; pause-alt = 󰏤
; play = 󰐍
; pause = 󰏦
; skip-next = 󰒭
; skip-prev = 󰒮

[module/spotify]
type = custom/script
exec = ~/.bin/polybar/spotify.sh
tail = true
label = %output%


; [module/spotify]
; type = custom/script
; exec = ~/.bin/polybar/spotify-playing.sh
; tail = true
; format-prefix = ${ic-launcher.spotify}
; format-prefix-font = 4
; format-prefix-padding = 1
; format-prefix-foreground = ${colors.ok}
; label = %output%
; label-font = 1
; ; scroll-up = playerctl next -p spotify
; ; scroll-down = playerctl previous -p spotify
;
; [module/spotify-prev]
; type = custom/text
; format = <label>
; label = ${ic-spotify.skip-prev}
; label-font = 4
; label-padding-left = 1
; click-left = playerctl next -p spotify
;
; [module/spotify-pp]
; type = custom/script
; exec = ~/.bin/polybar/spotify-playing.sh --pp-status --follow
; tail = true
; label = %output%
; label-font = 4
; ; label-padding-left = 1
; click-left = playerctl next -p spotify
;
; [module/spotify-next]
; type = custom/text
; format = <label>
; label = ${ic-spotify.skip-next}
; label-font = 4
; label-padding-right = 1
; click-left = playerctl previous -p spotify




