[ic-sysinfo]
memory = 󰍛
cpu = 󰻠

;----------------------------
;; CPU/RAM Usage
;----------------------------

[module/memory]
type = internal/memory
interval = 10

; format = " <label>"
; label = %percentage_used:2%%
; label-foreground = ${colors.fg}

format-prefix-font = 4
format-prefix = ${ic-sysinfo.memory}


label = %percentage_used:2%
label-font = 1

[module/cpu]
type = internal/cpu
interval = 10

format-prefix-font = 4
format-prefix = ${ic-sysinfo.cpu}


label = %percentage:2%
label-foreground = ${colors.fg}
label-font = 1


;----------------------------
;; Temperature CPU
;----------------------------

[module/cpu-temp]
type = internal/temperature
interval = 20
thermal-zone = 1
warn-temperature = 80
; warn-temperature = 10

format = "<label>"

label = %temperature-c%
label-font = 1

; cpu-temp warn-prefix
format-warn-prefix-font = 4
format-warn-prefix = 
format-warn-prefix-background = ${colors.crit}
format-warn-prefix-foreground = ${colors.fg-dark}
format-warn-prefix-overline = ${colors.warn}
format-warn-prefix-underline = ${colors.warn}
format-warn-prefix-padding = 2

format-warn = "<label-warn>"
; cpu-temp warn
label-warn = %temperature-c%
label-warn-foreground = ${colors.crit}
label-warn-background = ${colors.bg-alt}
label-warn-overline = ${colors.warn}
label-warn-underline = ${colors.warn}
label-warn-padding = 2
label-warn-font = 1
