;; ram (usage)
[module/memory]
type = internal/memory
interval = 5
format-prefix = "RAM"
format-prefix-foreground = ${colors.purple}
format-background = ${colors.background}
radius = 10
border-size = 2
format-prefix-font = 3
; format-prefix-background = ${colors.background-alt}
label = %percentage_used:2%%
label-warn = %percentage_used:2%%

;; cpu (usage)
[module/cpu]
type = internal/cpu
interval = 5
format-prefix = "CPU 󰻠 "
format-prefix-foreground = ${colors.primary}
label = %percentage:2%%
label-foreground = ${colors}

;; gpu - ADD + script
; [module/gpu]
