; transparent format = AARRGGBB
[colors]
bg = #CC2E3440
bg-alt = #CC3B4252
bg-hex = #2E3440
none = #0000003F
fg = #ECEFF4
fg-alt = #D8DEE9
fg-dark = #2E3440
accent = #81A1C1
accent-alt = #5E81AC
sep = #88C0D0

crit = #BF616A
warn = #EBCB8B
ok = #A3BE8C

; highlights
hilite = #B48EAD
hilite-alt = #9E4A8F
