# For a full list, see the wiki

# You can split this configuration into multiple files
# Create your files separately and then link them to this file like this:
# source = ~/.config/hypr/myColors.conf

################
### MONITORS ###
################

# See https://wiki.hypr.land/Configuring/Monitors/
# monitor=,preferred,auto,auto
monitor = DP-1,1920x1080@144,0x0,1,transform,1
monitor = DP-2,1920x1080@143.85,1080x0,1

###########################
### Load custom modules ###
###########################
source = ~/.config/hypr/configs/env.conf
source = ~/.config/hypr/configs/monitors.conf
source = ~/.config/hypr/configs/defaults.conf
source = ~/.config/hypr/configs/input.conf

source = ~/.config/hypr/configs/workspaces.conf
source = ~/.config/hypr/configs/binds.conf
source = ~/.config/hypr/configs/windowrules.conf

source = ~/.config/hypr/configs/decorations.conf
source = ~/.config/hypr/configs/animations.conf
source = ~/.config/hypr/configs/autostart.conf



# source = ~/.config/hypr/configs
##################
#### AUTOSTART ###
##################
#
## Autostart necessary processes (like notifications daemons, status bars, etc.)
## Or execute your favorite apps at launch like this:
#
## exec-once = $terminal
## exec-once = nm-applet &
## exec-once = waybar & hyprpaper & firefox
#exec-once = waybar &
#exec-once = $terminal
#exec-once = $firefox
###################
### PERMISSIONS ###
###################

# See https://wiki.hypr.land/Configuring/Permissions/
# Please note permission changes here require a Hyprland restart and are not applied on-the-fly
# for security reasons

# ecosystem {
#   enforce_permissions = 1
# }

# permission = /usr/(bin|local/bin)/grim, screencopy, allow
# permission = /usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland, screencopy, allow
# permission = /usr/(bin|local/bin)/hyprpm, plugin, allow
