# hyprpaper | https://wiki.hypr.land/Hypr-Ecosystem/hyprpaper/ #

ipc = true
splash = true
splash_opacity = 0.8
splash_offset = 20

wallpaper {
    monitor = DP-1
    path = ~/Pictures/hyprpaper/wife_flash_and_uap.png
    fit_mode = cover
}

wallpaper {
    monitor = DP-2
    path = ~/Pictures/hyprpaper/wife_and_flash.png
    fit_mode = cover
}
