### Permission ###
# https://wiki.hypr.land/

# https://wiki.hypr.land/Configuring/Permissions/
# permission modes: allow|ask|deny
# permission list: screencopy|plugin|keyboard
# e.g., 'permission = regex, permission, mode'

ecosystem {
    enforce_permissions = 1
}

# screencopy: printscrn to file|clipboard
permission = ^/usr/(bin|local/bin)/grim$, screencopy, allow
permission = ^/usr/(lib|libexec|lib64)/xdg-desktop-portal-hyprland$, screencopy, allow
permission = ^/usr/bin/hyprlock$, screencopy, allow

# plugins
permission = /usr/(bin|local/bin)/hyprpm, plugin, allow

# others: deny by default
permission = .*, plugin, deny

# Keywords | https://wiki.hypr.land/Configuring/Keywords/
$terminal = uwsm app -- kitty 
$wezterm = uwsm app -- wezterm
$filemanager = uwsm app -- thunar
$firefox = uwsm app -- firefox
$editor = uwsm app -- kitty -e nvim
$mailclient = uwsm app -- thunderbird

$waybar_reload = systemctl --user restart waybar.service

# Load config | e.g., 'source = ~/.config/hypr/configs'
# source = ~/.config/hypr/configs/theme.conf # colors|decorations|animations
source = ~/.config/hypr/configs/variables.conf  # variables
source = ~/.config/hypr/configs/animations/personal.conf # animations
source = ~/.config/hypr/configs/devices.conf  # monitors|keyboard|mouse|touch 
source = ~/.config/hypr/configs/binds.conf  # keybinds
source = ~/.config/hypr/configs/rules.conf # window|workspace-rule(s)
source = ~/.config/hypr/configs/session.conf # env|autostart


