# hyprsunset | https://wiki.hypr.land/Hypr-Ecosystem/hyprsunset/ #
# ipc = true
max-gamma = 100 # default 

profile {
    time = 7:00
    identity = true
    temperature = 7500 # default 6000
}

profile  {
    time = 18:00
    temperature = 4200
}

profile {
    time = 22:00
    temperature = 3400
}
