# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true # test ? remvove ?
palette = 'custom'
# command_timeout = 1500

format = '''
[┌──](fg:purple bold)$os $username $directory $git_branch$git_status
[│](fg:purple bold)$time
[└───](fg:purple bold)$character
'''

[palettes.custom]
foreground   = '#C9C8C8'
background   = '#15181C'
blue         = '#297594'
green        = '#4A6F3B'
orange       = '#CF8467'
# orange       = '#FFB86C' #not orange ?
purple       = '#AD73A9' #magneta
red          = '#AD5E5E'
yellow       = '#C9C984'

[character]
success_symbol = '[ ](fg:purple) '
error_symbol = '[](bold red) '
# 󰘍  󱞪   


## [EXAMPLE]
# format = '[─](fg:current_line)[](fg:yellow)[ ](fg:primary bg:yellow)[](fg:yellow bg:box)[ $user](fg:foreground bg:box)[](fg:box) '

[os]
# format = '[](fg:purple) [](fg:background)[ $symbol ](fg:red bg:background)[](fg:background)'
format = '[](fg:background)[ $symbol ](fg:red bg:background)[](fg:background)'
disabled = false

[username]
show_always = true
format = '[](fg:purple) [](fg:background)[  ](fg:foreground bg:background)[$user ](fg:orange bg:background bold)[](fg:background)'

[git_branch]
symbol = '󰊢 '
format = '[](fg:purple) [](fg:background)[ $symbol ](fg:purple bold bg:background)[$branch](fg:foreground bg:background italic)'


[git_status]
format      = '[$all_status $ahead_behind ](fg:green bg:background)[](fg:background)'
conflicted  = '  󱈸'
up_to_date  = ' 󰸞 '
deleted = '[  ](fg:red bg:background)'
untracked   = ' [ \($count\)](fg:foreground bg:background)'
modified    = '[  \($count\)](fg:yellow bg:background)'
staged      = '  ${count}'
renamed = '   '
ahead       = '⇡${count}'
diverged    = '  ⇡${ahead_count} ⇣${behind_count}'
behind      = ' ⇣${count}'

[directory]
format = '[](fg:purple) [](fg:background)[ $path](fg:orange bg:background)[$read_only ](fg:foreground bg:background)[](fg:background)'
home_symbol = "󰜥 "
truncation_symbol = ' ../'
truncation_length = 2
read_only = '󱧵 '

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = "  "
"Music" = "  "
"Pictures" = "  "

[os.symbols]
Arch = ' '
Debian = ' '
Fedora = ' '
Linux = ' '
Manjaro = ' '
Pop = ' '
Raspbian = ' '
Ubuntu = ' '
Unknown = ' '
Windows = ' '

[time]
disabled = false
format = '[ ](fg:purple) $time(fg:foreground bold)'
time_format = '%R'
utc_time_offset = '+2'

