# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

# Font opts: https://sw.kovidgoyal.net/kitty/conf/#fonts
disable_ligatures never

# Cursor: https://sw.kovidgoyal.net/kitty/conf/#text-cursor-customization
cursor_shape beam
cursor_shape_unfocused hollow
cursor_blink_interval -1

# Scroll: https://sw.kovidgoyal.net/kitty/conf/#scrollback
scrollback_lines 2000
scrollbar scrolled-and-hovered
scrollbar_interactive yes

# Mouse: https://sw.kovidgoyal.net/kitty/conf/#mouse
mouse_hide_wait 6.0
url_color #0087bd
url_style curly

# Performance: https://sw.kovidgoyal.net/kitty/conf/#performance-tuning
repaint_delay 10
input_delay 3
sync_to_monitor yes # set to false if screen-tearing

# Terminal bell: https://sw.kovidgoyal.net/kitty/conf/#terminal-bell
enable_audio_bell false
visual_bell_duration 0.1
visual_bell_color #ffffff
# bell_on_tab "ICON"

# Tab bar: https://sw.kovidgoyal.net/kitty/conf/#tab-bar
tab_bar_edge top
tab_bar_align right
tar_bar_min_tabs 2
tab_bar_style powerline
tab_powerline_style round

# OS tweaks: https://sw.kovidgoyal.net/kitty/conf/#os-specific-tweaks
wayland_titlebar_color system
linux_display_server auto

# theme

 include ./themes/catappuccin-frappe.conf


#
# disable_ligatures false
# scrollback_lines 10000
# copy_on_select true
# repaint_delay 2
# input_delay 1
#
# # draw_minmally no
# box_drawing_scale 0.001, 1, 1.5, 2
#
# # Pictures / Audio -
# enable_audio_bell no
# allow_remote_control yes
# sync_to_monitor yes
# visual_bell_duration 0.2
# visual_bell_color #ffffff
# draw_minimal_borders yes
# active_border_color #00ff00
#
# # SCROLLING
# scrollback_pager less
# scrollback_fill_enlarged_window yes
#
# #Term Windows
# hide_window_decorations titlebar-only
# window_padding_width 2
# enabled_layouts horizontal
#
# #tab bar
# tab_bar_edge top
# tab_bar_align right
# tab_bar_style  powerline
# remember_window_size  yes
# initial_window_width  900
# initial_window_height 600
#
# #keybinds
# map f1 new_tab
# map f2 next_tab
# map f3 new_tab  --location=vsplit
# map f6 launch --location=vsplit
# map F11 launch --type=overlay kitty @ set-colors --reload
# map f12 show_kitty_env_vars
#
# # MOVE BETWEEN PANES (SPLITS)
# map ctrl+left neighboring_window left
# map ctrl+right neighboring_window right
# map ctrl+up neighboring_window up
# map ctrl+down neighboring_window down
#
# #map f11 load_config ~/.config/kitty/kitty.conf
#
# map ctrl+shift+a new_window_with_cwd
# shell /bin/bash
#
# #Load theme
# include ./themes/catappuccin-frappe.conf

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
