# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

format = """
[╭](fg:current_line)\
$os\
$directory\
$git_branch\
$git_status\
$fill\
$nodejs\
$dotnet\
$python\
$java\
$c\
$cmd_duration\
$username\
$shell\
$time\
$line_break\
$character\
"""

palette = 'vscdark'
add_newline = true

[palettes.dracula]
foreground = '#F8F8F2'
background = '#282A36'
current_line = '#44475A'
primary = '#1E1F29'
box = '#44475A'
blue	= '#6272A4'
cyan = '#8BE9FD'
green	= '#50FA7B'
orange = '#FFB86C'
pink = '#FF79C6'
purple = '#BD93F9'
red	= '#FF5555'
yellow = '#F1FA8C'

[palettes.tokyo_night]
foreground = '#D8D8D8'
background = '#1A1B26'
current_line = '#2A2C37'
primary = '#292E42'
box = '#2A2C37'
blue = '#7AA2F7'
cyan = '#7FDBCA'
green = '#98C379'
orange = '#FF9E64'
pink = '#FF75A0'
purple = '#BB80B3'
red = '#F7768E'
yellow = '#E5C07B'
status = "#e23140"

[palettes.vscdark]
foreground   = '#F8F8F2'
#background   = '#3b3f4c'
background   = '#282A36'
current_line = '#44475A'
primary      = '#1E1F29'
box          = '#44475A'
blue         = '#6272A4'
cyan         = '#8BE9FD'
green        = '#50FA7B'
orange       = '#FFB86C'
pink         = '#FF79C6'
purple       = '#BD93F9'
red          = '#FF5555'
yellow       = '#F1FA8C'

[palettes.random]
black_gray = "#3b3f4c"
gray_white = "#dad7cd"
white = "#ffffff"
white_dark = "#dfe6e9"
blue_light = "#74b9ff"
blue = "#3a9efd"
orange = "#fca17d"
orange2 = "#db8a78"
orange3 = "#f4a261"
gray = "#3b3f4c"
gray_dark = "#282C34"
red_light = "#DA627D"
red = "#eb3b5a"
purple = "#ddacf5"
cyan = "#1ac0c6"

[os]
format = '(fg:current_line)[](fg:cyan)[$symbol ](fg:primary bg:cyan)[](fg:cyan)'
disabled = false

[os.symbols]
Alpine = ''
Amazon = ''
Android = ''
Arch = ''
CentOS = ''
Debian = ''
EndeavourOS = ''
Fedora = ''
FreeBSD = ''
Garuda = ''
Gentoo = ''
Linux = ''
Macos = ''
Manjaro = ''
Mariner = ''
Mint = ''
NetBSD = ''
NixOS = ''
OpenBSD = ''
OpenCloudOS = ''
openEuler = ''
openSUSE = ''
OracleLinux = '⊂⊃'
Pop = ''
Raspbian = ''
Redhat = ''
RedHatEnterprise = ''
Solus = ''
SUSE = ''
Ubuntu = ''
Unknown = ''
Windows = ''

[directory]
format = '[─](fg:current_line)[](fg:pink)[󰷏 ](fg:primary bg:pink)[](fg:pink bg:box)[ $read_only$truncation_symbol$path](fg:foreground bg:box)[](fg:box)'
home_symbol = " ~/"
truncation_symbol = ' '
truncation_length = 2
read_only = '󱧵 '
read_only_style = ''

[directory.substitutions]
"Documents" = "󰈙 doc"
"Downloads" = "  dl"
"Music" = " "
"Pictures" = "  pics"

[git_branch]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $branch](fg:foreground bg:box)[](fg:box)'
#symbol = '  '
symbol = ' '

[git_status]
format      = '[$all_status](fg:green bg:box)[](fg:box)'
conflicted  = ' '
up_to_date  = ' 󰸞'
untracked   = '  ${count}'
modified    = '  ${count}'
staged      = '  ${count}'
renamed     = '  '
deleted     = '  '
ahead       = ' ⇡${count}'
diverged    = '  ⇡${ahead_count} ⇣${behind_count}'
behind      = ' ⇣${count}'

[nodejs]
format = '[─](fg:current_line)[](fg:green)[$symbol](fg:primary bg:green)[](fg:green bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' Node.js'

[dotnet]
format = '[─](fg:current_line)[](fg:purple)[$symbol](fg:primary bg:purple)[](fg:purple bg:box)[ $tfm](fg:foreground bg:box)[](fg:box)'
symbol = ' .NET'

[c]
format = '[─](fg:current_line)[](fg:blue)[$symbol](fg:primary bg:blue)[](fg:blue bg:box)[ $version](fg:foreground bg:box)[](fg:box)'
symbol = ' C'

[fill]
symbol = '─'
style = 'fg:current_line'

[cmd_duration]
min_time = 500
format = '[─](fg:current_line)[](fg:orange)[ ](fg:primary bg:orange)[](fg:orange bg:box)[ $duration ](fg:foreground bg:box)[](fg:box)'

[shell]
format = '[─](fg:current_line)[](fg:blue)[ ](fg:primary bg:blue)[](fg:blue bg:box)[ $indicator](fg:foreground bg:box)[](fg:box)'
unknown_indicator = 'shell'
powershell_indicator = 'powershell'
fish_indicator = 'fish'
disabled = false

[time]
format = '[─](fg:current_line)[](fg:purple)[ ](fg:primary bg:purple)[](fg:purple bg:box)[ $time](fg:foreground bg:box)[](fg:box)'
time_format = '%H:%M'
disabled = false

[username]
format = '[─](fg:current_line)[](fg:yellow)[ ](fg:primary bg:yellow)[](fg:yellow bg:box)[ $user](fg:foreground bg:box)[](fg:box) '
show_always = true

[character]
format = """
[╰─$symbol](fg:current_line) """
success_symbol = '[](fg:bold green)'
error_symbol = '[×](fg:bold red)'
