return {
	{ "nvim-lua/plenary.nvim", lazy = true },
	{ "nvim-tree/nvim-web-devicons" },
	{ "b0o/schemastore.nvim", ft = { "json", "yaml" } },
	{ "folke/which-key.nvim", event = "VeryLazy", opts = { show_help = true, show_keys = true } },
	{ "rcarriga/nvim-notify", lazy = true, opts = { background_color = "#44444E" } },

	require("plugins.autopairs"),
	-- require("plugins.tabby"),
	require("plugins.bufferline"),
	require("plugins.cmp"),
	require("plugins.comments"),
	require("plugins.conform"),
	require("plugins.neotree"),
	require("plugins.winpicker"),
	require("plugins.rendermd"),
	require("plugins.git"),
	require("plugins.lualine"),
	require("plugins.mason"),
	require("plugins.noice"),
	require("plugins.spectre"),
	require("plugins.surround"),
	require("plugins.telescope"),
	require("plugins.treesitter"),
	require("plugins.yanky"),
	require("plugins.highlight"),
	require("plugins.themes"),
	require("plugins.colorizer"),
	-- undotree / telescope-undotree ?
}
