include-file = ~/.config/polybar/modules.ini

[colors]
bg = #CC111217
bg-alt = #CC1A1C22
fg = #E6EAF0
fg-dim = #A0A8B0
fg-dark = #0E0E0E

;accents / states
accent = #7FB4FF
ok = #79DCAA
warn = #FFD166
crit = #FF5C6D
sep =  #566070
hilite = #6B3F69

; groups
wifi = ${colors.accent}
audio = ${colors.accent}
time = ${colors.accent}
fs = ${colors.hilite}
mem = #456882
cpu = #A376A2
eth = #234C6A
wlan = #D2C1B6

i3-prefix = #222831
i3-prefix2 = #210F37
i3-prefix3 = #1D1616
i3-mode = #8ABEB7
i3-focus = #50589C
i3-unfocus = #393E46
i3-urgent = #842A3B

battery = ${colors.ok}
temp-warn = ${colors.warn}
temp-crit = ${colors.crit}




[global/wm]
margin-top = 0
margin-bottom = 0


[settings]
screenchange-reload = true
psuedo-transparency = true

[bar/base]
width = 100%
height = 30
fixed-center = true
background = ${colors.bg}
foreground = ${colors.fg}
separator = "  "
separator-foreground = ${colors.sep}
font-0 = "IosevkaTerm NFM:size=12;3"
font-1 = "IosevkaTerm NFM:size=12;3:weight=SemiBold"
font-2 = "JetBrainsMono NF:size=12;3:style=SemiBold"
font-3 = "Symbols Nerd Font:size=18;3"
; font-3 = "JetBrainsMono NF:size=14;3"
; font-3 = "IosevkaTerm NFM:size=20;6"

line-size = 1
border-size = 1
padding-left = 2
padding-right = 2
cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

;----------------------------
;; Top Bar
;----------------------------
[bar/top]
inherit = bar/base
monitor = "DP-2"
override-redirect = false

; replace i3 with the name of your i3 module
; scroll-up = "#i3.prev"
; scroll-down = "#i3.next"
; Alternatively, you can send commands directly to i3
;scroll-up = i3-msg workspace next_on_output
;scroll-down = i3-msg workspace prev_on_output

modules-left = i3 pulseaudio
modules-center = eth
modules-right = date powermenu

bottom = false
;; overwrite base
background = #00
padding-left = 0
module-margin-left = 1
module-margin-right = 2


;----------------------------
;; Top Bar
;----------------------------
[bar/bottom]
inherit = bar/base
monitor = "DP-2"
override-redirect = false
modules-left = filesystem
modules-center = memory
modules-right = cpu temperature
bottom = true
background = #00

; bg = #373B41
; bg-alt = #1B3C53
; fg_dark = #282A2E
; alert = #842A3B
; hilite = #6B3F69
; inactive_

; #1B3C53
; #234C6A
;#456882
; #D2C1B6
;
; #6B3F69
; #8D5F8C
; #A376A2
; #DDC3C3

; #FCF9EA


;;;;;;;;;;; OLD REMOVE BELOW ;;;;;;;;;;;;;;;

; [colors]
; background = #282A2E
; background-alt = #373B41
; foreground = #C5C8C6
; primary = #F0C674
; secondary = #8ABEB7
; alert = #A54242
; disabled = #707880
; active_hl = #89B4FA
; active_hl_fg = #3A3A3A
; inactive_hl= #A6ADC8
; base
;
;
; [bar/main]
; width = 100%
; height = 24pt
; radius = 6
;
; ; dpi = 96
;
; ; background = ${colors.background}
; background = #00
; foreground = ${colors.foreground}
;
; line-size = 3pt
;
; border-size = 4pt
; border-color = #00000000
;
; padding-left = 0
; padding-right = 1
;
; module-margin = 1
;
; separator = |
; separator-foreground = ${colors.disabled}
;
; font-0 = monospace;2
; ; scroll-up = i3wm-wsnext
; ; scroll-down = i3wm-wsprev
; ; tray-position = right
; ; tray-padding = 2
;
; ; modules-left = xworkspaces xwindow
;
; modules-left = xworkspaces
; modules-right = filesystem pulseaudio memory cpu eth date
;
; cursor-click = pointer
; cursor-scroll = ns-resize
;
; enable-ipc = true
;
; [module/systray]
; type = internal/tray
;
; format-margin = 8pt
; tray-spacing = 16pt
;
;
; [module/filesystem]
; type = internal/fs
; interval = 50
;
; ; mount-0 = /
; mount-0 = /media/veracrypt1/
; mount-1 = /media/veracrypt2/
;
; label-mounted = %{F#F0C674}%mountpoint%%{F-} %percentage_used%%
;
; label-unmounted = %mountpoint% not mounted
; label-unmounted-foreground = ${colors.disabled}
;
; [module/pulseaudio]
; type = internal/pulseaudio
;
; format-volume-prefix = "VOL "
; format-volume-prefix-foreground = ${colors.primary}
; format-volume = <label-volume>
;
; label-volume = %percentage%%
;
; label-muted = muted
; label-muted-foreground = ${colors.disabled}
;
;
;
; [module/memory]
; type = internal/memory
; interval = 2
; format-prefix = "RAM "
; format-prefix-foreground = ${colors.primary}
; label = %percentage_used:2%%
;
; [module/cpu]
; type = internal/cpu
; interval = 2
; format-prefix = "CPU "
; format-prefix-foreground = ${colors.primary}
; label = %percentage:2%%
;
; [network-base]
; type = internal/network
; interval = 5
; format-connected = <label-connected>
; format-disconnected = <label-disconnected>
; label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
;
; ; [module/wlan]
; ; inherit = network-base
; ; interface-type = wireless
; ; label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%
;
; [module/eth]
; inherit = network-base
; interface-type = wired
; label-connected-prefix = "ETH: "
; label-connected = %local_ip%
; ; label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
;
; [module/date]
; type = internal/date
; interval = 1
;
; date = %H:%M
; date-alt = %Y-%m-%d %H:%M:%S
;
; label = %date%
; label-foreground = ${colors.primary}
;
; [settings]
; screenchange-reload = true
; pseudo-transparency = true
;

