; load all modules for bar-cfgs
; include-file = ~/.config/polybar/modules/audio.ini
; include-file = ~/.config/polybar/modules/datetime.ini
; include-file = ~/.config/polybar/modules/fs.ini
; include-file = ~/.config/polybar/modules/i3.ini
; include-file = ~/.config/polybar/modules/launcher.ini
; include-file = ~/.config/polybar/modules/network.ini
; include-file = ~/.config/polybar/modules/powermenu.ini
; include-file = ~/.config/polybar/modules/sysinfo.ini
; include-file = ~/.config/polybar/modules/xkeyboard.ini
; include-file = ~/.config/polybar/modules/spotify.ini
; include-file = ~/.config/polybar/modules/kdeconnect.ini

; load theme, general icons and bars to be loaded.
; required by modules to load theme here
; include-file = ~/.config/polybar/icons.ini
include-file = ~/.config/polybar/themes/nord.ini
include-file = ~/.config/polybar/bars/bubbles.ini

[global/wm]
margin-top = 0
margin-bottom = 0




