; load all modules for bar-cfgs
include-file = ~/.config/polybar/modules/audio.ini
include-file = ~/.config/polybar/modules/datetime.ini
include-file = ~/.config/polybar/modules/fs.ini
include-file = ~/.config/polybar/modules/i3.ini
include-file = ~/.config/polybar/modules/launcher.ini
include-file = ~/.config/polybar/modules/network.ini
; include-file = ~/.config/polybar/modules/powerline.ini
include-file = ~/.config/polybar/modules/powermenu.ini
include-file = ~/.config/polybar/modules/sysinfo.ini
include-file = ~/.config/polybar/modules/xkeyboard.ini
include-file = ~/.config/polybar/modules/spotify.ini
include-file = ~/.config/polybar/modules/kdeconnect.ini

; load theme, general icons and bars to be loaded.
; required by modules to load theme here
include-file = ~/.config/polybar/themes/nord.ini
include-file = ~/.config/polybar/icons.ini
include-file = ~/.config/polybar/bars/mainbars.ini


[global/wm]
margin-top = 0
margin-bottom = 0

[settings]
screenchange-reload = true
; psuedo-transparency = true

[bar/base]
width = 100%
height = 25
fixed-center = true
background = ${colors.bg}
foreground = ${colors.fg}
separator = "  "
; separator-foreground = ${colors.sep}

font-0 = "IosevkaTerm NFM:size=11;3"
font-1 = "IosevkaTerm NFM:size=14;3:weight=Bold"
font-2 = "JetBrainsMono NF:size=12;3:style=SemiBold"
font-3 = "Symbols Nerd Font:size=16;3"
font-4 = "Symbols Nerd Font:size=18;3"

cursor-click = pointer
cursor-scroll = ns-resize
enable-ipc = true

line-size = 2



