;; find modules info and more:
; https://github.com/polybar/polybar/wiki

; include-file = ~/.config/polybar/icons.ini

;; Bar default background = bg
;; Modules = bg-alt (needs to be set)
;; default text color/foreground = colors.fg
;; all modules icon (size 14px+) font: font = 4
;; other text defaults to font-0 if not set

;----------------------------
;; Icons
;----------------------------
;; ${icons-mdi.NAME}
[icons-mdi]
; apps
; home = 󰟒
; firefox = 󰈹
; steam = 󰓓
; terminal = 󰞷
; spotify = 󰓇
; utils
; celsius_temp = 󰔄
; check = 󰄬
; check_bold = 󰸞
; arrow_down = 󰜯
; arrow_up = 󰜸
; notify_new = 󰎔
; clock = 󱑂
; clock_outline = 󱑎
; calender = 󰸗
; exclamation = 󱈸
; cog = 󰢻
; workspaces = 󰙀
; hardware
; memory = 󰍛
; cpu = 󰻠
; hdd = 󰋊
; hdd_remove = 󱁌
; hdd_add = 󱁋
; keyboard = 󰌓

;eth cable
; eth_ip = 󰩟
; eth_upspeed = 󰜸
; eth_downspeed = 󰜯
; cable_connected = 󰈁
; cable_disconnected = 󰈂

;eth wlan
; network-strength-1 = 󰣴
; network-strength-2 = 󰣶
; network-strength-3 = 󰣸
; network-strength-4 = 󰣺
; network-strength-4-alert = 󰣻
; network-strength-off = 󰣼
; network-strength-off-outline = 󰣽

; power
; power = 󰐥
; sleep = 󰤄
; restart = 󰜉

; sound
; volume-high = 󰕾
; volume-low = 󰕿
; volume-medium = 󰖀
; volume-mute = 󰝟
; volume-off = 󰖁
; volume-source = 󱄠
;
; drag-vertical-bar = 󱋱
; drag-vertical-bar-dotted = 󰇝
; drag-horizontal-bar = 󰇜
; drag-horizontal-bar-dotted = 󰇜
; drag-horizontal-line = 󰅹
# bluetooth
; bluetooth = 󰂯
; bluetooth_off = 󰂲


; [icons-nf-powerline]
; pixelated_square_big = 
; pixelated_square_big_mirror = 
; pixelated_square_small = 
; pixelated_square_small_mirror = 
; half_circle_thin_right = 
; half_circle_thin_left = 
; half_circle_thick_right = 
; half_circle_thick_left = 

; [powerline-base]
; type = custom/text
; format-font = 4
;
; [module/pl-menu-pixel-right]
; inherit = powerline-base
; format = ${icons-nf-powerline.pixelated_square_big}
; format-foreground = ${colors.bar-menu-pl-ic}
;
; [module/pl-menu-pixel-left]
; inherit = powerline-base
; format = ${icons-nf-powerline.pixelated_square_big_mirror}
; format-foreground = ${icons-nf-powerline.bar-menu-pl-ic}
;----------------------------
;; Workspaces
;----------------------------

; [module/i3]
; type = internal/i3
; ; pin-workspaces = true
; show-urgent = true
; strip-wsnumbers = true
; index-sort = true
; enable-click = false
; enable-scroll = false
; wrapping-scroll = false
; reverse-scroll = false
; fuzzy-match = true
;
; ; ws-icon-0 = 1;
; ; ws-icon-1 = 2;
; ; ws-icon-2 = 3;󰪶
; ; ws-icon-3 =4;
; ; ws-icon-4 = 5;󱍋
; ; ws-icon-default = 
; ws-icon-0 = 1
; ws-icon-1 = 2
; ws-icon-2 = 3
; ws-icon-3 = 4
; ws-icon-4 = 5
;
;
; format = <label-state> <label-mode>
; format-prefix = ${icons-mdi.workspaces}
; ; format-prefix = 
; ; format-prefix-background = ${colors.i3-prefix}
; format-prefix-font = 4
; format-prefix-padding = 1
;
; label-mode = %mode%
; label-mode-padding = 1
; label-mode-background = ${colors.i3-mode}
; ; label-mode-overline = ${colors.hilite}
; ; label-mode-underline = ${colors.hilite}
; label-mode-font = 1
;
; label-focused = %name%
; ; label-focused-background = ${colors.i3-focus}
; ; label-focused-underline = ${colors.hilite}
; label-focused-underline = ${colors.i3-focus}
; label-focused-padding = 1
; label-focused-font = 1
;
; ; unfocused = inactive ws on any monitor
; format-unfocused-background = ${colors.crit}
; label-unfocused = %index%
; label-unfocused-padding = 1
; label-unfocused-font = 4
;
; ; visible = active ws on onfocused monitor
; label-visible = %name%
; label-visible-padding = 1
; ; label-visible-background = ${colors.i3-visible}
; label-visible-font = 1
;
; label-urgent = %index%
; label-urgent-background = ${colors.i3-urgent}
; label-urgent-padding = 3
; label-urgent-font = 4

;----------------------------
;; CPU/RAM Usage
;----------------------------

; [module/memory]
; type = internal/memory
; interval = 10
;
; ; format = " <label>"
; ; label = %percentage_used:2%%
; ; label-foreground = ${colors.fg}
;
; format-prefix-font = 4
; format-prefix = ${icons-mdi.memory}
; ; format-prefix = 
; ; format-prefix-padding = 1
; ; format-prefix-background = ${colors.mem}
; ; format-prefix-overline = ${colors.mem}
; ; format-prefix-underline = ${colors.mem}
; ; format-background = ${colors.bg-alt}
;
; label = %percentage_used:2%
; ; label-background = ${colors.hilite}
; ; label-underline = ${colors.mem}
; ; label-overline = ${colors.mem}
; ; label-padding = 2
; label-font = 1
;
; [module/cpu]
; type = internal/cpu
; interval = 10
;
; format-prefix-font = 4
; format-prefix = ${icons-mdi.cpu}
; ; format-prefix = 󰻠
; ; format-prefix-padding = 1
; ; format-prefix-background = ${colors.cpu}
; ; format-prefix-foreground = ${colors.fg-dark}
; ; format-prefix-overline = ${colors.cpu}
; ; format-prefix-underline = ${colors.cpu}
;
; label = %percentage:2%
; label-foreground = ${colors.fg}
; label-font = 1
; ; label-background = ${colors.bg-alt}
; ; label-overline = ${colors.cpu}
; ; label-underline = ${colors.cpu}

; ;----------------------------
; ;; Network Connections
; ;----------------------------
;
; [network-base]
; type = internal/network
; interval = 5
; format-connected = <label-connected>
; format-disconnected = <label-disconnected>
; label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%
; label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected
;
; ; wireless = laptop
; [module/wlan]
; inherit = network-base
; interface-type = wireless
;
; format-connected = <ramp-signal> <label-connected>
;
; label-disconnected =
; ;label-disconnected = ${icons-mdi.network-strength-off}
; label-disconnected-font = 4
; label-disconnected-foreground = ${colors.crit}
;
; ramp-signal-0 = ${icons-mdi.network-strength-1}
; ramp-signal-1 = ${icons-mdi.network-strength-2}
; ramp-signal-2 = ${icons-mdi.network-strength-3}
; ramp-signal-3 = ${icons-mdi.network-strength-4}
;
; animation-packetloss-0 = ${icons-mdi.network-strength-4-alert}
; animation-packetloss-0-foreground = ${colors.warn}
; animation-packetloss-1 = ${icons-mdi.exclamation}
; animation-packetloss-1-foreground = ${colors.warn}
; animation-packetloss-framrate = 500
;
;
; ; cable = desktop
; [module/eth]
; inherit = network-base
; interface-type = wired
;
; format-connected-prefix-font = 4
; format-connected-prefix = ${icons-mdi.eth_ip}
; format-connected-prefix-foreground = ${colors.ok}
; format-connected-prefix-padding = 1
;
; label-connected = %local_ip%
; label-padding = 1
;
; label-disconnected = ${icons-mdi.cable_disconnected}
; label-disconnected-foreground = ${colors.crit}
;
; [module/eth-upspeed]
; inherit = network-base
; interface-type = wired
; accumulate-stats = true
; unknown-as-up = true
;
; format-connected-prefix-font = 4
; format-connected-prefix = ${icons-mdi.eth_upspeed}
; format-connected-prefix-foreground = ${colors.warn}
; format-connected-prefix-padding-right = 1
; label-connected =  %upspeed%
; label-disconnected =
;
; [module/eth-downspeed]
; inherit = network-base
; interface-type = wired
; accumulate-stats = true
; unknown-as-up = true
;
; format-connected-prefix-font = 4
; format-connected-prefix = ${icons-mdi.eth_downspeed}
; format-connected-prefix-foreground = ${colors.ok}
; format-connected-prefix-padding-right = 1
; format-connected = <label-connected>
; label-connected =  %downspeed%
; label-disconnected =

; ;----------------------------
; ;; Filesystem
; ;----------------------------
; [fs-base]
; type = internal/fs
; interval = 50
; fixed-values = true
;
; ; nf-fa-hard_drive
; ; format-mounted-prefix = 
; format-mounted-prefix-font = 4
; format-mounted-prefix = ${icons-mdi.hdd}
; format-mounted-prefix-padding = 1
; format-mounted = <label-mounted>
; format-mounted-prefix-foreground = ${colors.ok}
;
; label-mounted-padding = 1
; label-mounted-font = 1
;
; ; nf-fa-xmark
; ; format-unmounted-prefix = 
; format-unmounted-prefix-font = 4
; format-unmounted-prefix = ${icons-mdi.hdd_remove}
; format-unmounted-prefix-padding = 1
; format-unmounted-prefix-foreground = ${colors.crit}
; format-unmounted = <label-unmounted>
;
; label-unmounted =  %mountpoint%
; label-unmounted-foreground = ${colors.fg-dim}
; label-unmounted-font = 1
;
; [module/fs-root]
; inherit = fs-base
; mount-0 = /
; label-mounted = / %free%
;
; ; TODO: add custom .sh-script to get whole disk space ? or not ?
; [module/fs-ext]
; inherit = fs-base
; mount-0 = /media/veracrypt2
; label-mounted = ext/ %free%




; ;----------------------------
; ;; Date / Time
; ;----------------------------
;
; [date-base]
; type = internal/date
; interval = 1
;
; [module/time]
; inherit = date-base
; time = %H:%M
;
; format = <label>
; format-prefix-font = 4
; format-prefix = ${icons-mdi.clock_outline}
; format-prefix-padding-right = 1
;
; label = %time%
; label-font = 1
;
; [module/date]
; inherit = date-base
; date = %Y-%m-%d%
;
; format = <label>
; format-prefix-font = 4
; format-prefix = ${icons-mdi.calender}
; format-prefix-padding-right = 1
;
; label = %date%
; label-font = 1

; ;----------------------------
; ;; Audio / PulseAudio / PipeWire
; ;----------------------------
; [module/pulseaudio]
; type = internal/pulseaudio
; ; match interval with bar-volume-foreground-*
; interval = 20
;
; format-volume = <ramp-volume> <label-volume> <bar-volume>
; format-volume-foreground = ${colors.fg}
;
; ; nf-fa-volume_up
; ; format-volume-prefix = 
; ; format-volume-prefix-font = 4
; ; format-volume-prefix-padding-right = 1
; ; format-volume-underline = ${colors.ok}
; label-volume = %percentage%%
; ; label-volume-foreground = ${colors.ok}
;
; ; nf-fa-volume_xmark
; ; format-muted-prefix = 
; format-muted-prefix = ${icons-mdi.volume-mute}
; format-muted-prefix-font = 4
; format-muted-prefix-padding-right = 1
; format-muted-foreground = ${colors.fg-dim}
; ; format-muted-underline = ${colors.crit}
;
; label-muted = muted
; ; label-muted =
; laber-muted-foreground = ${colors.warn}
;
; bar-volume-width = 5
; bar-volume-foreground-0 = ${colors.hilite}
; bar-volume-foreground-1 = ${colors.hilite}
; bar-volume-foreground-2 = ${colors.hilite}
; bar-volume-foreground-3 = ${colors.hilite}
; bar-volume-foreground-4 = ${colors.hilite}
;
; ; bar-volume-foreground-5 = ${colors.hilite}
; ; bar-volume-foreground-6 = ${colors.hilite}
; bar-volume-gradient = false
;
; ; nf-md-drag-vertical_variant
; ; bar-volume-indicator = 󱋱
; bar-volume-indicator = ${icons-mdi.drag-vertical-bar}
; bar-volume-indicator-font = 4
; bar-volume-indicator-foreground = ${colors.fg}
; ; nf-md-drag-horizontal_variant: 󱋰
;
; ; nf-oct-horizontal_rule
; ; bar-volume-fill = 
; bar-volume-fill = ${icons-mdi.drag-horizontal-line}
; bar-volume-fill-font = 4
;
; ; format-bar-volume-empty-foreground = ${colors.warn}
; ; bar-volume-empty = 
; bar-volume-empty = ${icons-mdi.drag-horizontal-line}
; bar-volume-empty-font = 4
; bar-volume-empty-foreground = ${colors.fg-dim}
;
; ramp-volume-0 = ${icons-mdi.volume-low}
; ramp-volume-1 = ${icons-mdi.volume-medium}
; ramp-volume-2 = ${icons-mdi.volume-high}
; ramp-volume-font = 4
;
;
; click-right = pavucontrol

;----------------------------
;; Temperature(s)
;----------------------------

; [module/cpu-temp]
; type = internal/temperature
; interval = 20
; thermal-zone = 1
; warn-temperature = 80
; ; warn-temperature = 10
;
; ; format-prefix-font = 4
; ; format-prefix = 
; ; format-prefix-background = ${colors.ok}
; ; format-prefix-foreground = ${colors.fg-dark}
; ; format-prefix-overline = ${colors.ok}
; ; format-prefix-underline = ${colors.ok}
; ; format-prefix-padding = 2
; format = "<label>"
;
; label = %temperature-c%
; ; label-background = ${colors.bg-alt}
; ; label-overline = ${colors.ok}
; ; label-underline = ${colors.ok}
; ; label-padding = 2
; label-font = 1
;
; ; cpu-temp warn-prefix
; format-warn-prefix-font = 4
; format-warn-prefix = 
; format-warn-prefix-background = ${colors.temp-crit}
; format-warn-prefix-foreground = ${colors.fg-dark}
; format-warn-prefix-overline = ${colors.temp-warn}
; format-warn-prefix-underline = ${colors.temp-warn}
; format-warn-prefix-padding = 2
;
; format-warn = "<label-warn>"
; ; cpu-temp warn
; label-warn = %temperature-c%
; label-warn-foreground = ${colors.crit}
; label-warn-background = ${colors.bg-alt}
; label-warn-overline = ${colors.temp-warn}
; label-warn-underline = ${colors.temp-warn}
; label-warn-padding = 2
; label-warn-font = 1

;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; CUSTOM MODULES BELOW
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

;----------------------------
;; Power (on/off/sleep)
;----------------------------

; [module/powermenu]
; type = custom/text
; format = ${icons-mdi.power}
; ; format = 
; ; format-foreground = ${colors.fg}
; format-padding = 1
; format-font = 4
;
; ; format-background = ${colors.bg-alt}
; ; format-underline = ${colors.crit}
; ; format-overline = ${colors.crit}
;
; ; click-left = ~/.config/polybar/scripts/powermenu.sh

;----------------------------
;; Applications + .sh-scripts
;----------------------------
; [open-base]
; type = custom/text
; format-font = 4
; ; format-padding-left= 1
;
; ;;; TEMPLATE ;;;
; ; [module/open_???]
; ; inherit = open-base
; ; format = 
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"
;
; [module/open_home]
; inherit = open-base
; format = ${icons-mdi.home}
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"
;
; [module/open_firefox]
; inherit = open-base
; format = ${icons-mdi.firefox}
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"
;
; [module/open_steam]
; inherit = open-base
; format = ${icons-mdi.steam}
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"
;
; [module/open_term]
; inherit = open-base
; format = ${icons-mdi.terminal}
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"
;
; [module/open_spotify]
; inherit = open-base
; format = ${icons-mdi.spotify}
; ; click-left = ~/.config/polybar/scripts.open.sh "cmd"




;nf-fa-percent: 
