;; find modules info and more:
; https://github.com/polybar/polybar/wiki


;; Bar default background = bg
;; Modules = bg-alt (needs to be set)
;; default text color/foreground = colors.fg
;; all modules icon (size 14px+) font: font = 4
;; other text defaults to font-0 if not set

;----------------------------
;; Workspaces
;----------------------------

; [module/xworkspaces]
; type = internal/xworkspaces
; ; pin-workspaces = true
; enable-click = true
; ; enable-scroll = true
; label-active = %name%
;
; label-active-background = ${colors.hilite}
; ; label-active-foreground = ${colors.????????}
; label-active-padding = 1
;
; label-occupied = %name%
; label-occupied-padding = 1
;
; label-urgent = %name%
; label-urgent-background = ${colors.alert}
; label-urgent-padding = 1
;
; label-empty = %name%
; label-empty-foreground = ${colors.disabled}
; label-empty-padding = 1

[module/i3]
type = internal/i3
; pin-workspaces = true
show-urgent = true
strip-wsnumbers = true
index-sort = true
enable-click = false
enable-scroll = false
wrapping-scroll = false
reverse-scroll = false
fuzzy-match = true


format = <label-state> <label-mode>
format-prefix =  󰵮
format-prefix-background = ${colors.i3-prefix}
format-prefix-font = 4
format-prefix-padding = 1

format-overline = ${colors.hilite}
format-underline = ${colors.hilite}
format-background = ${colors.i3-unfocus}
format-line-size = 3
; format-font = 3
; format-ws-icon-font = 4

ws-icon-1 = 1;
ws-icon-0 = 2;
ws-icon-2 = 3;󰪶
ws-icon-3 = 4;
ws-icon-4 = 5;󱍋
ws-icon-default = 
; ws-icon-font = 4


label-mode =  %mode%
label-mode-padding = 2
label-mode-background = ${colors.i3-mode}
label-mode-overline = ${colors.i3-mode}
label-mode-underline = ${colors.i3-mode}
label-mode-font = 4

; label-focused = %index%
label-focused = %icon%
label-focused-foreground = ${colors.fg-dark}
label-focused-background = ${colors.i3-focus}
label-focused-padding = 4
label-focused-font = 4
; label-focused-underline = ${colors.hilite}
; label-focused-overline =  ${colors.hilite}



; label-unfocused = %index%
label-unfocused = %icon%
label-unfocused-foreground = ${colors.fg-dim}
label-unfocused-background = ${colors.i3-unfocus}
label-unfocused-padding = 2
label-unfocused-font = 4

label-visible = %icon%
label-visible-padding = 1
label-visible-font = 4

; label-urgent = %index%

label-urgent = %icon%
label-urgent-background = ${colors.i3-urgent}
label-urgent-padding = 3
label-urgent-font = 4
; label-urgent-foreground = ${colors.???}
;----------------------------
;; Memory / RAM
;----------------------------

[module/memory]
type = internal/memory
interval = 10
; format = " <label>"
; label = %percentage_used:2%%
; label-foreground = ${colors.fg}
format-prefix-font = 4
format-prefix = 
format-prefix-padding = 1
format-prefix-background = ${colors.mem}
format-prefix-overline = ${colors.mem}
format-prefix-underline = ${colors.mem}
; format-background = ${colors.bg-alt}

label = Usage: %percentage_used:2%%
label-background = ${colors.hilite}
label-underline = ${colors.mem}
label-overline = ${colors.mem}
label-padding = 2
label-font = 2

[module/cpu]
type = internal/cpu
interval = 10

format-prefix-font = 4
format-prefix = 󰻠
format-prefix-padding = 1
format-prefix-background = ${colors.cpu}
; format-prefix-foreground = ${colors.fg-dark}
format-prefix-overline = ${colors.cpu}
format-prefix-underline = ${colors.cpu}

label = %percentage:2%%
label-foreground = ${colors.fg}
label-background = ${colors.bg-alt}
label-overline = ${colors.cpu}
label-underline = ${colors.cpu}
label-padding = 2
label-font = 2

;----------------------------
;; Network Connections
;----------------------------

[network-base]
type = internal/network
interval = 5
format-connected = <label-connected>
format-disconnected = <label-disconnected>
label-disconnected = %{F#F0C674}%ifname%%{F#707880} disconnected

; wireless = laptop
[module/wlan]
inherit = network-base
interface-type = wireless

format-connected-prefix-font = 4
format-connected-prefix =

label-connected = %{F#F0C674}%ifname%%{F-} %essid% %local_ip%

; cable = desktop
[module/eth]
inherit = network-base
interface-type = wired

; nf-fa-ethernet = 󰈀
; nf-fa-network_wired = 
format-connected-prefix-font = 4
format-connected-prefix = 󰈀
format-connected-prefix-background = ${colors.eth}
format-connected-prefix-underline = ${colors.eth}
format-connected-prefix-overline = ${colors.eth}
format-connected-prefix-padding = 1

label-connected = %{F#F0C674}%ifname%%{F-} %local_ip%
label-background = ${colors.bg-alt}
label-overline = ${colors.eth}
label-underline = ${colors.eth}
label-padding = 2
label-font = 2


format-disconnected-prefix-font = 4
format-disconnected-prefix =

label-disconnected =

;----------------------------
;; Filesystem
;----------------------------
[module/filesystem]
type = internal/fs
mount-0 = /media/veracrypt2/
interval = 50
fixed-values = true
spacing = 2

format-mounted-prefix-font = 4
format-mounted-prefix = 
format-mounted-prefix-padding = 1
format-mounted-prefix-background = ${colors.fs}
format-mounted-background = ${colors.bg-alt}
format-mounted-overline = ${colors.fs}
format-mounted-underline = ${colors.fs}
format-mounted = <label-mounted>

label-mounted =  %mountpoint%: %percentage_used% of %total%
label-mounted-padding = 1
label-mounted-font = 2

format-unmounted-prefix-font = 4
format-unmounted-prefix = 
format-unmounted-prefix-padding = 1
format-unmounted-prefix-background = ${colors.fs}
format-unmounted-overline = ${colors.fs}
format-unmounted-underline = ${colors.fs}
format-unmounted = <label-unmounted>

label-unmounted-prefix-font = 4
label-unmounted-prefix = 
label-unmounted =  %mountpoint%: not mounted
label-unmounted-foreground = ${colors.fg-dim}
label-unmounted-background = ${colors.bg-alt}
label-unmounted-padding = 1
label-unmounted-font = 2


;----------------------------
;; Date / Time
;----------------------------

[module/date]
type = internal/date
interval = 1
time = %H:%M
; date =

format = <label>
format-prefix = 
format-prefix-background = ${colors.time}
format-prefix-padding = 2
format-prefix-overline = ${colors.time}
format-prefix-underline = ${colors.time}
format-overline = ${colors.hilite}
format-underline = ${colors.hilite}

label = %time%
label-foreground = ${colors.fg}
label-background = ${colors.bg-alt}
label-padding = 1
format-prefix-font = 4

;----------------------------
;; Audio / PulseAudio / PipeWire
;----------------------------
[module/pulseaudio]
type = internal/pulseaudio
; list with: pacmd list-sinks
; sink = ???

format-volume-prefix-font = 4
format-volume-prefix = 󰝝
format-volume-prefix-padding = 1
format-volume-prefix-background = ${colors.audio}
format-volume-overline = ${colors.audio}
format-volume-underline = ${colors.audio}
format-volume-background = ${colors.bg-alt}
format-volume-foreground = ${colors.fg}
format = <label-volume> <bar-volume>

label-volume = %percentage%%
label-volume-background = ${colors.bg-alt}
label-volume-padding = 1

format-muted-prefix-font = 4
format-muted-prefix = 󰝟
format-muted-prefix-padding = 1
format-muted-prefix-background = ${colors.fg-dim}
format-muted-overline = ${colors.warn}
format-muted-underline = ${colors.warn}
format-muted-background = ${colors.bg-alt}
format-muted = <label-muted>

label-muted = "Off"
label-muted-foreground = ${colors.warn}
label-muted-padding = 1

click-right = pavucontrol

;----------------------------
;; Temperature(s)
;----------------------------

[module/temperature]
type = internal/temperature
interval = 20
thermal-zone = 1
warn-temperature = 10

format-prefix-font = 4
format-prefix = 
format-prefix-background = ${colors.ok}
format-prefix-foreground = ${colors.fg-dark}
format-prefix-overline = ${colors.ok}
format-prefix-underline = ${colors.ok}
format-prefix-padding = 2
format = "<label>"

label = %temperature-c%
label-background = ${colors.bg-alt}
label-overline = ${colors.ok}
label-underline = ${colors.ok}
label-padding = 2
label-font = 2

format-warn-prefix-font = 4
format-warn-prefix = 
format-warn-prefix-background = ${colors.temp-warn}
format-warn-prefix-foreground = ${colors.fg-dark}
format-warn-prefix-overline = ${colors.temp-warn}
format-warn-prefix-underline = ${colors.temp-warn}
format-warn-prefix-padding = 2

format-warn = "<label-warn>"

label-warn = %temperature-c%
label-warn-foreground = ${colors.crit}
label-warn-background = ${colors.bg-alt}
label-warn-overline = ${colors.temp-warn}
label-warn-underline = ${colors.temp-warn}
label-warn-padding = 2
label-warn-font = 2

;----------------------------
;; Power (on/off/sleep)
;----------------------------

[module/powermenu]
type = custom/text
format = "󰐥"
format-foreground = ${colors.fg}
format-background = ${colors.bg-alt}
format-underline = ${colors.crit}
format-overline = ${colors.crit}
format-padding = 1
format-font = 4
; click-left = ~/.config/polybar/scripts/powermenu.sh
tooltip = Power
