# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]; then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Optional: disable systemd pager
# export SYSTEMD_PAGER=

# Load modular user bash config from ~/.bash/
for rc in bash_aliases bash_exports bash_fzf; do
    file="$HOME/.bash/$rc"
    [[ -f "$file" ]] && source "$file"
done

# fzf completion
[ -f ~/.fzf.bash ] && source ~/.fzf.bash

# starship
eval "$(starship init bash)"
